#!/usr/bin/env python3
"""Regenerate the Java 21 identifier alphabet from Python's Unicode 15 database.

Run from any directory with Python 3.12 (unicodedata 15.0.0).
The Java Character category rules are defined by isJavaIdentifierStart/Part;
identifier-ignorable control/format characters are deliberately excluded.
"""
import pathlib
import unicodedata

if unicodedata.unidata_version != "15.0.0":
    raise SystemExit("Expected Unicode 15.0.0; refusing to change the language alphabet implicitly")

start = {"Lu", "Ll", "Lt", "Lm", "Lo", "Nl", "Sc", "Pc"}
part = start | {"Mn", "Mc", "Nd"}

def ranges(categories):
    result = []
    begin = previous = None
    for point in range(0x110000):
        if unicodedata.category(chr(point)) in categories:
            if begin is None:
                begin = point
            previous = point
        elif begin is not None:
            result.extend((begin, previous))
            begin = previous = None
    if begin is not None:
        result.extend((begin, previous))
    return result

text = """// Copyright 2026 Danny Reinhold
// SPDX-License-Identifier: Apache-2.0
package org.vernac.language;

// Generated by tools/generate_unicode_tables.py. Do not edit by hand.
// Java 21 / Unicode 15.0; excludes control, format and identifier-ignorable characters.
final class Unicode15Identifiers {
    private Unicode15Identifiers() { }
"""
for name, categories in (("START", start), ("PART", part)):
    values = ranges(categories)
    text += "    static final int[] " + name + " = {\n"
    for index in range(0, len(values), 12):
        text += "        " + ", ".join(f"0x{value:X}" for value in values[index:index+12]) + ",\n"
    text += "    };\n"
text += "}\n"
output = pathlib.Path(__file__).resolve().parents[1] / "src/main/java/org/vernac/language/Unicode15Identifiers.java"
output.write_text(text, encoding="utf-8")
