package org.vernac.compiler.generator;

import com.palantir.javapoet.*;
import org.jspecify.annotations.Nullable;
import org.vernac.compiler.ast.*;
import org.vernac.compiler.util.TypeUtils;
import org.vernac.runtime.AggregateRoot;
import org.vernac.runtime.DomainEvent;
import org.vernac.runtime.DomainValidationException;

import javax.lang.model.element.Modifier;
import java.time.Instant;
import java.util.*;

public class AggregateGenerator {

    private static final ClassName AGGREGATE_ROOT_INTERFACE = ClassName.get(AggregateRoot.class);
    private static final ClassName DOMAIN_EVENT_INTERFACE = ClassName.get(DomainEvent.class);
    private static final ClassName NULLABLE_ANNOTATION = ClassName.get(Nullable.class);

    public JavaFile generate(AggregateNode node, Map<String, ValueObjectNode> valueObjects, Map<String, EntityNode> entities, String basePackage, List<String> imports) {
        String targetPackage = PackageResolver.resolveDomainPackage(basePackage, node.customPackage());

        String className = node.name();
        ClassName selfType = ClassName.get(targetPackage, className);

        TypeName idType = TypeResolver.resolve(node.idDefinition().type(), targetPackage, imports);
        String idFieldName = node.idDefinition().fieldName();

        ParameterizedTypeName aggregateRootType = ParameterizedTypeName.get(AGGREGATE_ROOT_INTERFACE, idType);

        String tableName = PostgresSchemaUtils.resolveTableName(className);
        String idColName = PostgresSchemaUtils.resolveColumnName(idFieldName);
        String ddl = PostgresSchemaUtils.generateAggregateDdl(tableName, idColName, node.fields(), valueObjects, entities, targetPackage);

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(aggregateRootType)
                .addJavadoc("Aggregate Root generated by Vernac DSL Compiler. Do not edit.\n\n")
                .addJavadoc("<p>Expected PostgreSQL Table Schema:</p>\n<pre>{@code\n$L\n}</pre>\n", ddl);

        // Schema- und Tabellenkonstanten
        classBuilder.addField(FieldSpec.builder(String.class, "TABLE_NAME", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("$S", tableName)
                .build());

        classBuilder.addField(FieldSpec.builder(String.class, "SCHEMA_DDL", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("$S", ddl)
                .build());

        // 1. Metadaten-Felder
        TypeName listOfEvents = ParameterizedTypeName.get(ClassName.get(List.class), DOMAIN_EVENT_INTERFACE);
        classBuilder.addField(FieldSpec.builder(listOfEvents, "domainEvents", Modifier.PRIVATE, Modifier.FINAL, Modifier.TRANSIENT)
                .initializer("new $T<>()", ArrayList.class)
                .build());

        classBuilder.addField(FieldSpec.builder(Instant.class, "createdAt", Modifier.PRIVATE, Modifier.FINAL).build());
        classBuilder.addField(FieldSpec.builder(Instant.class, "updatedAt", Modifier.PRIVATE).build());
        classBuilder.addField(FieldSpec.builder(long.class, "version", Modifier.PRIVATE).build());

        // 2. ID-Feld
        classBuilder.addField(FieldSpec.builder(idType, idFieldName, Modifier.PRIVATE, Modifier.FINAL).build());

        // 3. Fachliche Felder
        for (FieldNode field : node.fields()) {
            TypeName fieldType = TypeResolver.resolve(field.type(), targetPackage);
            List<Modifier> modifiers = new ArrayList<>();
            modifiers.add(Modifier.PRIVATE);
            if (!field.isMutable()) {
                modifiers.add(Modifier.FINAL);
            }

            FieldSpec.Builder fieldBuilder = FieldSpec.builder(fieldType, field.name(), modifiers.toArray(Modifier[]::new));
            if (field.type().isOptional()) {
                fieldBuilder.addAnnotation(NULLABLE_ANNOTATION);
            }
            classBuilder.addField(fieldBuilder.build());
        }

        // 4. Privater Konstruktor
        classBuilder.addMethod(buildPrivateConstructor(node, targetPackage, idType, idFieldName));

        // 5. Validierungsmethode
        classBuilder.addMethod(buildValidateMethod(node));

        // 6. create(...) Factory
        classBuilder.addMethod(buildCreateFactory(node, targetPackage, selfType, idType, idFieldName));

        // 7. reconstitute(...) Factory & withVersion
        classBuilder.addMethod(buildReconstituteFactory(node, targetPackage, selfType, idType, idFieldName));
        classBuilder.addMethod(buildWithVersionMethod(node, selfType, idFieldName));

        // 8. fromExternal(...) Factory
        classBuilder.addMethod(buildFromExternalFactory(node, targetPackage, selfType, idType, idFieldName));

        // 9. Event Management
        classBuilder.addMethod(buildRegisterEventMethod());
        classBuilder.addMethod(buildPullDomainEventsMethod());

        // 10. markAsUpdated & automatische Setter ohne set-Präfix
        boolean hasMutableFields = node.fields().stream().anyMatch(FieldNode::isMutable);
        if (hasMutableFields) {
            classBuilder.addMethod(buildMarkAsUpdatedMethod());
        }

        Set<String> explicitMethodNames = node.methods().stream()
                .map(MethodNode::name)
                .collect(java.util.stream.Collectors.toSet());

        for (FieldNode field : node.fields()) {
            if (field.isMutable() && !explicitMethodNames.contains(field.name())) {
                classBuilder.addMethod(buildDomainMutator(field, targetPackage));
            }
        }

        // 11. Fachmethoden aus der DSL
        for (MethodNode method : node.methods()) {
            classBuilder.addMethod(buildCustomMethod(method, targetPackage));
        }

        // 12. Getter für Metadaten & Id
        classBuilder.addMethod(buildIdGetter(idType, idFieldName));

        classBuilder.addMethod(MethodSpec.methodBuilder("createdAt")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(Instant.class)
                .addStatement("return this.createdAt")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("updatedAt")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(Instant.class)
                .addStatement("return this.updatedAt")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("version")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(long.class)
                .addStatement("return this.version")
                .build());

        for (FieldNode field : node.fields()) {
            classBuilder.addMethod(buildFieldGetter(field, targetPackage));
        }

        // 13. equals, hashCode (auf ID-Basis) & toString
        classBuilder.addMethod(buildEquals(selfType, idFieldName));
        classBuilder.addMethod(buildHashCode(idFieldName));
        classBuilder.addMethod(buildToString(className, idFieldName));

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildPrivateConstructor(AggregateNode node, String targetPackage, TypeName idType, String idFieldName) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .addParameter(idType, idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            constructor.addParameter(param.build());
        }

        constructor.addParameter(Instant.class, "createdAt");
        constructor.addParameter(Instant.class, "updatedAt");
        constructor.addParameter(long.class, "version");
        constructor.addParameter(boolean.class, "validate");

        constructor.addStatement("this.$N = $T.requireNonNull($N, $S)", idFieldName, Objects.class, idFieldName, idFieldName + " must not be null");

        for (FieldNode field : node.fields()) {
            if (field.type().isOptional()) {
                constructor.addStatement("this.$N = $N", field.name(), field.name());
            } else if (TypeUtils.isPrimitive(field.type().name())) {
                constructor.addStatement("this.$N = $N", field.name(), field.name());
            } else {
                constructor.addStatement("this.$N = $T.requireNonNull($N, $S)", field.name(), Objects.class, field.name(), field.name() + " must not be null");
            }
        }

        constructor.addStatement("this.createdAt = $T.requireNonNull(createdAt, $S)", Objects.class, "createdAt must not be null");
        constructor.addStatement("this.updatedAt = $T.requireNonNull(updatedAt, $S)", Objects.class, "updatedAt must not be null");
        constructor.addStatement("this.version = version");

        constructor.beginControlFlow("if (validate)");
        constructor.addStatement("validate()");
        constructor.endControlFlow();

        return constructor.build();
    }

    private MethodSpec buildValidateMethod(AggregateNode node) {
        MethodSpec.Builder validate = MethodSpec.methodBuilder("validate")
                .addModifiers(Modifier.PRIVATE);

        for (ValidationRuleNode rule : node.validations()) {
            validate.beginControlFlow("if (!($L))", rule.condition());
            validate.addStatement("throw new $T($S)", DomainValidationException.class, rule.message());
            validate.endControlFlow();
        }

        return validate.build();
    }

    private MethodSpec buildCreateFactory(AggregateNode node, String targetPackage, ClassName selfType, TypeName idType, String idFieldName) {
        MethodSpec.Builder create = MethodSpec.methodBuilder("create")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(idType, idFieldName);

        List<String> passArgs = new ArrayList<>();
        passArgs.add(idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            create.addParameter(param.build());
            passArgs.add(field.name());
        }

        passArgs.add("now");
        passArgs.add("now");
        passArgs.add("0L");
        passArgs.add("true");

        create.addStatement("$T now = $T.now()", Instant.class, Instant.class);
        create.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return create.build();
    }

    private MethodSpec buildReconstituteFactory(AggregateNode node, String targetPackage, ClassName selfType, TypeName idType, String idFieldName) {
        MethodSpec.Builder reconstitute = MethodSpec.methodBuilder("reconstitute")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(idType, idFieldName);

        List<String> passArgs = new ArrayList<>();
        passArgs.add(idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            reconstitute.addParameter(param.build());
            passArgs.add(field.name());
        }

        reconstitute.addParameter(Instant.class, "createdAt");
        reconstitute.addParameter(Instant.class, "updatedAt");
        reconstitute.addParameter(long.class, "version");

        passArgs.add("createdAt");
        passArgs.add("updatedAt");
        passArgs.add("version");
        passArgs.add("false");

        reconstitute.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return reconstitute.build();
    }

    private MethodSpec buildRegisterEventMethod() {
        return MethodSpec.methodBuilder("registerEvent")
                .addModifiers(Modifier.PROTECTED)
                .addParameter(DOMAIN_EVENT_INTERFACE, "event")
                .addStatement("$T.requireNonNull(event, $S)", Objects.class, "event must not be null")
                .addStatement("this.domainEvents.add(event)")
                .build();
    }

    private MethodSpec buildPullDomainEventsMethod() {
        TypeName listOfEvents = ParameterizedTypeName.get(ClassName.get(List.class), DOMAIN_EVENT_INTERFACE);
        return MethodSpec.methodBuilder("pullDomainEvents")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(listOfEvents)
                .addStatement("$T events = $T.copyOf(this.domainEvents)", listOfEvents, List.class)
                .addStatement("this.domainEvents.clear()")
                .addStatement("return events")
                .build();
    }

    private MethodSpec buildMarkAsUpdatedMethod() {
        return MethodSpec.methodBuilder("markAsUpdated")
                .addModifiers(Modifier.PROTECTED)
                .addStatement("this.updatedAt = $T.now()", Instant.class)
                .build();
    }

    private MethodSpec buildDomainMutator(FieldNode field, String targetPackage) {
        TypeName type = TypeResolver.resolve(field.type(), targetPackage);
        MethodSpec.Builder setter = MethodSpec.methodBuilder(field.name())
                .addModifiers(Modifier.PUBLIC);

        ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());

        if (field.type().isOptional()) {
            param.addAnnotation(NULLABLE_ANNOTATION);
            setter.addParameter(param.build());
            setter.beginControlFlow("if ($T.equals(this.$N, $N))", Objects.class, field.name(), field.name());
            setter.addStatement("return");
            setter.endControlFlow();
            setter.addStatement("this.$N = $N", field.name(), field.name());
        } else if (TypeUtils.isPrimitive(field.type().name())) {
            setter.addParameter(param.build());
            setter.beginControlFlow("if (this.$N == $N)", field.name(), field.name());
            setter.addStatement("return");
            setter.endControlFlow();
            setter.addStatement("this.$N = $N", field.name(), field.name());
        } else {
            setter.addParameter(param.build());
            setter.addStatement("$T.requireNonNull($N, $S)", Objects.class, field.name(), field.name() + " must not be null");
            setter.beginControlFlow("if ($T.equals(this.$N, $N))", Objects.class, field.name(), field.name());
            setter.addStatement("return");
            setter.endControlFlow();
            setter.addStatement("this.$N = $N", field.name(), field.name());
        }

        setter.addStatement("markAsUpdated()");
        setter.addStatement("validate()");
        return setter.build();
    }

    private MethodSpec buildCustomMethod(MethodNode method, String targetPackage) {
        TypeName returnType = TypeResolver.resolve(method.returnType(), targetPackage);
        MethodSpec.Builder builder = MethodSpec.methodBuilder(method.name())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType);

        for (FieldNode param : method.parameters()) {
            TypeName paramType = TypeResolver.resolve(param.type(), targetPackage);
            builder.addParameter(paramType, param.name());
        }

        builder.addCode(method.bodyCode() + "\n");
        return builder.build();
    }

    private MethodSpec buildIdGetter(TypeName idType, String idFieldName) {
        return MethodSpec.methodBuilder("id")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(idType)
                .addStatement("return this.$N", idFieldName)
                .build();
    }

    private MethodSpec buildFieldGetter(FieldNode field, String targetPackage) {
        TypeName baseType = TypeResolver.resolve(field.type(), targetPackage);
        MethodSpec.Builder getter = MethodSpec.methodBuilder(field.name())
                .addModifiers(Modifier.PUBLIC);

        if (field.type().isOptional()) {
            TypeName optionalType = ParameterizedTypeName.get(ClassName.get(Optional.class), baseType);
            getter.returns(optionalType);
            getter.addStatement("return $T.ofNullable(this.$N)", Optional.class, field.name());
        } else {
            getter.returns(baseType);
            getter.addStatement("return this.$N", field.name());
        }

        return getter.build();
    }

    private MethodSpec buildEquals(ClassName selfType, String idFieldName) {
        return MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(Object.class, "o")
                .addStatement("if (this == o) return true")
                .addStatement("if (o == null || getClass() != o.getClass()) return false")
                .addStatement("$T that = ($T) o", selfType, selfType)
                .addStatement("return $T.equals(this.$N, that.$N)", Objects.class, idFieldName, idFieldName)
                .build();
    }

    private MethodSpec buildWithVersionMethod(AggregateNode agg, ClassName selfType, String idFieldName) {
        MethodSpec.Builder mb = MethodSpec.methodBuilder("withVersion")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(TypeName.LONG, "newVersion");

        List<String> args = new ArrayList<>();
        args.add("this." + idFieldName);
        for (FieldNode f : agg.fields()) {
            args.add("this." + f.name());
        }
        args.add("this.createdAt");
        args.add("this.updatedAt");
        args.add("newVersion");
        args.add("false");

        mb.addStatement("return new $T($L)", selfType, String.join(", ", args));
        return mb.build();
    }

    private MethodSpec buildHashCode(String idFieldName) {
        return MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class)
                .addStatement("return $T.hash(this.$N)", Objects.class, idFieldName)
                .build();
    }

    private MethodSpec buildToString(String className, String idFieldName) {
        return MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return $S + this.$N + \"]\"", className + "[id=", idFieldName)
                .build();
    }

    private MethodSpec buildFromExternalFactory(AggregateNode node, String targetPackage, ClassName selfType, TypeName idType, String idFieldName) {
        MethodSpec.Builder fromExternal = MethodSpec.methodBuilder("fromExternal")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(idType, idFieldName);

        List<String> passArgs = new ArrayList<>();
        passArgs.add(idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            fromExternal.addParameter(param.build());
            passArgs.add(field.name());
        }

        passArgs.add("Instant.now()");
        passArgs.add("Instant.now()");
        passArgs.add("0L");
        passArgs.add("true");

        fromExternal.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return fromExternal.build();
    }
}