package org.vernac.compiler.generator;

import com.palantir.javapoet.*;
import org.vernac.compiler.ast.*;
import org.vernac.compiler.util.ConditionUtils;
import org.vernac.compiler.util.TypeUtils;
import org.vernac.runtime.DomainValidationException;

import javax.lang.model.element.Modifier;
import java.util.List;
import java.util.Map;
import java.util.Objects;

public class DomainServiceGenerator {

    private static final ClassName SERVICE_ANNOTATION = ClassName.get("org.springframework.stereotype", "Service");

    public JavaFile generate(
            DomainServiceNode node,
            Map<String, AggregateNode> aggregates,
            String basePackage,
            List<String> explicitImports
    ) {
        String domainPackage = PackageResolver.resolveDomainPackage(basePackage, node.customPackage());
        String className = node.name();

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(SERVICE_ANNOTATION)
                .addJavadoc("Domain Service generated by Vernac DSL Compiler. Do not edit.\n");

        boolean hasTupleReturn = node.returnStatement().isPresent()
                && node.returnStatement().get() instanceof TupleReturnNode;

        // 1. Eingebetteter Result-Record bei Tuple-Returns
        if (hasTupleReturn) {
            TupleReturnNode tuple = (TupleReturnNode) node.returnStatement().get();
            classBuilder.addType(buildEmbeddedResultRecord(tuple, node, aggregates, domainPackage, explicitImports));
        }

        // 2. Haupt-Ausführungsmethode (execute)
        classBuilder.addMethod(buildExecuteMethod(node, hasTupleReturn, domainPackage, explicitImports));

        return JavaFile.builder(domainPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildExecuteMethod(
            DomainServiceNode node,
            boolean hasTupleReturn,
            String domainPackage,
            List<String> explicitImports
    ) {
        MethodSpec.Builder execute = MethodSpec.methodBuilder("execute")
                .addModifiers(Modifier.PUBLIC);

        // A. Rückgabetyp bestimmen
        if (hasTupleReturn) {
            execute.returns(ClassName.get("", "Result"));
        } else if (node.returnType().isPresent()) {
            execute.returns(TypeResolver.resolve(node.returnType().get(), domainPackage, explicitImports));
        } else if (node.returnStatement().isPresent() && node.returnStatement().get() instanceof SingleReturnNode single && single.expressionCode().isPresent()) {
            // Typ-Inferenz Fallback für Single-Return
            TypeName inferred = inferTypeFromExpression(single.expressionCode().get(), node, domainPackage, explicitImports);
            execute.returns(inferred);
        } else {
            execute.returns(TypeName.VOID);
        }

        // B. Parameter anlegen & null-checks generieren
        for (FieldNode param : node.parameters()) {
            TypeName paramType = TypeResolver.resolve(param.type(), domainPackage, explicitImports);
            execute.addParameter(paramType, param.name());

            if (!TypeUtils.isPrimitive(param.type().name())) {
                execute.addStatement("$T.requireNonNull($L, $S)", Objects.class, param.name(), param.name() + " must not be null");
            }
        }

        // C. Validierungsregeln
        for (ValidationRuleNode rule : node.validations()) {
            String msg = rule.message().isBlank() ? "Validation failed for: " + rule.condition() : rule.message();
            execute.beginControlFlow("if ($L)", ConditionUtils.negate(rule.condition()))
                    .addStatement("throw new $T($S)", DomainValidationException.class, msg)
                    .endControlFlow();
        }

        // D. Statements generieren
        for (UseCaseStatementNode stmt : node.statements()) {
            if (stmt instanceof RawJavaStatementNode raw) {
                execute.addCode(raw.javaCode() + "\n");
            }
        }

        // E. Return-Statement generieren
        if (node.returnStatement().isPresent()) {
            ReturnStatementNode ret = node.returnStatement().get();
            if (ret instanceof SingleReturnNode single) {
                if (single.expressionCode().isPresent()) {
                    execute.addStatement("return $L", single.expressionCode().get());
                } else {
                    execute.addStatement("return");
                }
            } else if (ret instanceof TupleReturnNode tuple) {
                List<String> args = tuple.elements().stream()
                        .map(TupleElementNode::expressionCode)
                        .toList();
                execute.addStatement("return new Result($L)", String.join(", ", args));
            }
        }

        return execute.build();
    }

    private TypeSpec buildEmbeddedResultRecord(
            TupleReturnNode tuple,
            DomainServiceNode node,
            Map<String, AggregateNode> aggregates,
            String domainPackage,
            List<String> explicitImports
    ) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder();

        for (TupleElementNode elem : tuple.elements()) {
            String fieldName = elem.alias().orElseGet(() -> deriveTupleFieldName(elem.expressionCode()));
            TypeName type = inferTypeFromExpression(elem.expressionCode(), node, domainPackage, explicitImports);
            constructor.addParameter(type, fieldName);
        }

        return TypeSpec.recordBuilder("Result")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .recordConstructor(constructor.build())
                .build();
    }

    private TypeName inferTypeFromExpression(
            String expr,
            DomainServiceNode node,
            String domainPackage,
            List<String> explicitImports
    ) {
        String trimmed = expr.trim();
        for (FieldNode param : node.parameters()) {
            if (param.name().equals(trimmed)) {
                return TypeResolver.resolve(param.type(), domainPackage, explicitImports);
            }
        }
        if (trimmed.startsWith("\"") && trimmed.endsWith("\"")) return ClassName.get(String.class);
        if (trimmed.matches("-?\\d+")) return TypeName.INT;
        if (trimmed.matches("-?\\d+\\.\\d+")) return TypeName.DOUBLE;
        if (trimmed.matches("true|false")) return TypeName.BOOLEAN;

        return TypeName.get(Object.class);
    }

    private String deriveTupleFieldName(String expr) {
        String code = expr.trim();
        int dot = code.lastIndexOf('.');
        if (dot >= 0) {
            String candidate = code.substring(dot + 1).replaceAll("[^a-zA-Z0-9_]", "");
            return candidate.isEmpty() ? "value" : candidate;
        }
        return code.replaceAll("[^a-zA-Z0-9_]", "");
    }
}