// Copyright 2026 Danny Reinhold
// SPDX-License-Identifier: Apache-2.0
package org.vernac.compiler.generator;

import com.palantir.javapoet.*;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;
import org.vernac.compiler.ast.*;
import org.vernac.compiler.pipeline.ResolvedProject;
import org.vernac.compiler.symbols.TypeIdentity;
import org.vernac.runtime.DomainCollections;
import javax.lang.model.element.Modifier;
import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Stream;

/** One generator for lists/sets of IDs, values, enums, entities and aggregates. */
public final class DomainCollectionGenerator {
    private static ParameterizedTypeName generic(Class<?> raw, TypeName argument) {
        return ParameterizedTypeName.get(ClassName.get(raw), argument);
    }

    public JavaFile generate(CollectionDeclaration collection, String namespace, ResolvedProject project) {
        ClassName item = ResolvedJavaTypes.domainClass(new TypeIdentity(namespace, collection.elementName()));
        ClassName self = ResolvedJavaTypes.domainClass(new TypeIdentity(namespace, collection.name()));
        boolean list = collection.definition().kind() == CollectionDefinitionNode.Kind.LIST;
        TypeName storage = generic(list ? List.class : Set.class, item);
        TypeName iterable = generic(Iterable.class, WildcardTypeName.subtypeOf(item));
        TypeName optional = generic(Optional.class, item);
        TypeSpec.Builder type = TypeSpec.classBuilder(self).addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addAnnotation(NullMarked.class).addSuperinterface(generic(Iterable.class, item))
                .addJavadoc("Immutable $L structure for $T. Element instances are not copied. Generated by Vernac.\n",
                        list ? "list" : "set", item)
                .addField(storage, "items", Modifier.PRIVATE, Modifier.FINAL);
        type.addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).addParameter(iterable, "items")
                .addStatement("this.items = $T.$L(items)", DomainCollections.class, list ? "list" : "set").build());
        type.addMethod(MethodSpec.methodBuilder("of").addModifiers(Modifier.PUBLIC, Modifier.STATIC).returns(self)
                .addParameter(iterable, "items").addStatement("return new $T(items)", self).build());
        type.addMethod(MethodSpec.methodBuilder("of").addModifiers(Modifier.PUBLIC, Modifier.STATIC).returns(self)
                .addParameter(ArrayTypeName.of(item), "items").varargs(true)
                .addStatement("return new $T($T.asList($T.required(items)))", self, Arrays.class, DomainCollections.class).build());
        type.addMethod(MethodSpec.methodBuilder("empty").addModifiers(Modifier.PUBLIC, Modifier.STATIC).returns(self)
                .addStatement("return new $T($T.of())", self, List.class).build());
        type.addMethod(method("size", TypeName.INT).addStatement("return items.size()").build());
        type.addMethod(method("isEmpty", TypeName.BOOLEAN).addStatement("return items.isEmpty()").build());
        type.addMethod(method("contains", TypeName.BOOLEAN).addParameter(item, "element")
                .addStatement("return items.contains($T.required(element))", DomainCollections.class).build());
        type.addMethod(method("count", TypeName.INT).addParameter(item, "element")
                .addStatement("return $T.count(items, element)", DomainCollections.class).build());
        type.addMethod(method("find", optional).addParameter(item, "element")
                .addStatement("return $T.find(items, element)", DomainCollections.class).build());
        type.addMethod(method(list ? "asList" : "asSet", storage).addStatement("return items").build());
        type.addMethod(method("stream", generic(Stream.class, item)).addStatement("return items.stream()").build());
        type.addMethod(method("iterator", generic(Iterator.class, item)).addAnnotation(Override.class)
                .addStatement("return items.iterator()").build());
        type.addMethod(method("plus", self).addParameter(item, "element")
                .addStatement("return plusAll($T.of($T.required(element)))", List.class, DomainCollections.class).build());
        type.addMethod(method("plusAll", self).addParameter(iterable, "elements")
                .addStatement("return new $T($T.plusAll(items, elements))", self, DomainCollections.class).build());
        type.addMethod(method("minus", self).addParameter(item, "element")
                .addStatement("return new $T($T.minus(items, element))", self, DomainCollections.class).build());
        type.addMethod(method("minusAll", self).addParameter(item, "element")
                .addStatement("return minusAll($T.of($T.required(element)))", List.class, DomainCollections.class).build());
        type.addMethod(method("minusAll", self).addParameter(iterable, "elements")
                .addStatement("return new $T($T.matching(items, elements, false))", self, DomainCollections.class).build());
        type.addMethod(method("matching", self).addParameter(item, "element")
                .addStatement("return matching($T.of($T.required(element)))", List.class, DomainCollections.class).build());
        type.addMethod(method("matching", self).addParameter(iterable, "elements")
                .addStatement("return new $T($T.matching(items, elements, true))", self, DomainCollections.class).build());
        type.addMethod(method("filter", self).addParameter(generic(Predicate.class, WildcardTypeName.supertypeOf(item)), "predicate")
                .addStatement("return new $T(items.stream().filter($T.required(predicate)).toList())", self, DomainCollections.class).build());
        if (list) {
            type.addMethod(method("get", item).addParameter(int.class, "index").addStatement("return items.get(index)").build());
            type.addMethod(method("first", optional).addStatement("return items.stream().findFirst()").build());
            type.addMethod(method("last", optional)
                    .addStatement("return items.isEmpty() ? $T.empty() : $T.of(items.get(items.size() - 1))", Optional.class, Optional.class).build());
            type.addMethod(method("distinct", self)
                    .addStatement("return new $T($T.set(items))", self, DomainCollections.class).build());
            type.addMethod(method("duplicates", self)
                    .addJavadoc("Returns every occurrence of each repeated equality group, preserving order and instances.\n"
                            + "For one representative per repeated group, use duplicates().distinct().\n")
                    .addStatement("return new $T($T.duplicates(items))", self, DomainCollections.class).build());
        }
        if (collection.idType().isPresent()) {
            TypeName id = ResolvedJavaTypes.javaType(project.typeOf(collection.idType().get()));
            type.addMethod(method("by", optional).addParameter(id, "id")
                    .addStatement("$T.required(id)", DomainCollections.class)
                    .addStatement("return items.stream().filter(element -> element.id().equals(id)).findFirst()").build());
            type.addMethod(method("contains", TypeName.BOOLEAN).addParameter(id, "id")
                    .addStatement("return by(id).isPresent()").build());
            type.addMethod(method("minusId", self).addParameter(id, "id")
                    .addStatement("return by(id).map(this::minus).orElse(this)").build());
            type.addMethod(method("minusAllId", self).addParameter(id, "id")
                    .addStatement("$T.required(id)", DomainCollections.class)
                    .addStatement("return filter(element -> !element.id().equals(id))").build());
        }
        type.addMethod(method("equals", TypeName.BOOLEAN).addAnnotation(Override.class)
                .addParameter(ParameterSpec.builder(Object.class, "other").addAnnotation(Nullable.class).build())
                .addStatement("if (this == other) return true")
                .addStatement("return other instanceof $T that && items.equals(that.items)", self).build());
        type.addMethod(method("hashCode", TypeName.INT).addAnnotation(Override.class).addStatement("return items.hashCode()").build());
        type.addMethod(method("toString", ClassName.get(String.class)).addAnnotation(Override.class)
                .addStatement("return $S + items", collection.name()).build());
        for (MethodNode custom : collection.definition().customMethods()) {
            TypeName returnType = ResolvedJavaTypes.javaType(project.typeOf(custom.returnType()));
            if (custom.returnType().isOptional()) returnType = generic(Optional.class, returnType);
            MethodSpec.Builder m = MethodSpec.methodBuilder(custom.name()).returns(returnType);
            if (!custom.accessModifier().equals("internal")) m.addModifiers(Modifier.valueOf(custom.accessModifier().toUpperCase(Locale.ROOT)));
            for (FieldNode parameter : custom.parameters()) {
                TypeName parameterType = ResolvedJavaTypes.javaType(project.typeOf(parameter.type()));
                if (parameter.type().isOptional()) parameterType = parameterType.annotated(AnnotationSpec.builder(Nullable.class).build());
                m.addParameter(parameterType, parameter.name());
            }
            type.addMethod(m.addCode("$L\n", custom.bodyCode()).build());
        }
        return JavaFile.builder(self.packageName(), type.build()).indent("    ").skipJavaLangImports(true).build();
    }

    private MethodSpec.Builder method(String name, TypeName returns) {
        return MethodSpec.methodBuilder(name).addModifiers(Modifier.PUBLIC).returns(returns);
    }

    public String determineCollectionClassName(EntityNode node) { return node.collection().orElseThrow().nameFor(node.name()); }
    public String determineCollectionClassName(ValueObjectNode node) { return node.collection().orElseThrow().nameFor(node.name()); }
}
