// Copyright 2026 Danny Reinhold
// SPDX-License-Identifier: Apache-2.0

package org.vernac.compiler.generator;

import com.palantir.javapoet.*;
import org.vernac.compiler.ast.EntityNode;
import org.vernac.compiler.ast.FieldNode;
import org.vernac.compiler.ast.MethodNode;
import org.vernac.compiler.ast.ValueObjectNode;

import javax.lang.model.element.Modifier;
import java.util.*;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.stream.Stream;

public class DomainCollectionGenerator {

    public JavaFile generate(ValueObjectNode node, String basePackage, List<String> explicitImports) {
        String targetPackage = PackageResolver.resolveCollectionPackage(basePackage, node.collection(), Optional.empty());
        String itemClassName = node.name();
        String collectionClassName = determineCollectionClassName(node);

        ClassName itemType = ClassName.get(targetPackage, itemClassName);
        ClassName selfType = ClassName.get(targetPackage, collectionClassName);

        TypeName listOfItems = ParameterizedTypeName.get(ClassName.get(List.class), itemType);
        TypeName collectionOfItems = ParameterizedTypeName.get(ClassName.get(Collection.class), itemType);
        TypeName iterableOfItems = ParameterizedTypeName.get(ClassName.get(Iterable.class), itemType);
        TypeName setOfItems = ParameterizedTypeName.get(ClassName.get(Set.class), itemType);
        TypeName arrayListOfItems = ParameterizedTypeName.get(ClassName.get(ArrayList.class), itemType);

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(collectionClassName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(iterableOfItems)
                .addJavadoc("First-class domain collection for {@link $T}. Generated by Vernac DSL Compiler. Do not edit.\n", itemType);

        // Internes Feld: private final List<Item> items;
        classBuilder.addField(FieldSpec.builder(listOfItems, "items", Modifier.PRIVATE, Modifier.FINAL).build());

        // Privater Konstruktor mit List.copyOf
        classBuilder.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .addParameter(collectionOfItems, "items")
                .addStatement("$T.requireNonNull(items, $S)", Objects.class, "items must not be null")
                .addStatement("this.items = $T.copyOf(items)", List.class)
                .build());

        // Factories
        classBuilder.addMethod(MethodSpec.methodBuilder("empty")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addStatement("return new $T($T.of())", selfType, List.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .varargs(true)
                .addParameter(ArrayTypeName.of(itemType), "items")
                .addStatement("$T.requireNonNull(items, $S)", Objects.class, "items must not be null")
                .addStatement("return new $T($T.asList(items))", selfType, Arrays.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(collectionOfItems, "items")
                .addStatement("return new $T(items)", selfType)
                .build());

        // Standard-Queries & Immutability Exports
        classBuilder.addMethod(MethodSpec.methodBuilder("mutableCopy")
                .addModifiers(Modifier.PRIVATE)
                .returns(arrayListOfItems)
                .addStatement("return new $T<>(this.items)", ArrayList.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("size")
                .addModifiers(Modifier.PUBLIC)
                .returns(int.class)
                .addStatement("return this.items.size()")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("isEmpty")
                .addModifiers(Modifier.PUBLIC)
                .returns(boolean.class)
                .addStatement("return this.items.isEmpty()")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("contains")
                .addModifiers(Modifier.PUBLIC)
                .returns(boolean.class)
                .addParameter(itemType, "item")
                .addStatement("return this.items.contains(item)")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("stream")
                .addModifiers(Modifier.PUBLIC)
                .returns(ParameterizedTypeName.get(ClassName.get(Stream.class), itemType))
                .addStatement("return this.items.stream()")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("toList")
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfItems)
                .addJavadoc("Returns an unmodifiable list of the underlying items.\n")
                .addStatement("return this.items")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("elements")
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfItems)
                .addJavadoc("Returns an unmodifiable list of the underlying elements.\n")
                .addStatement("return this.items")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("toSet")
                .addModifiers(Modifier.PUBLIC)
                .returns(setOfItems)
                .addJavadoc("Returns an unmodifiable set of the underlying items.\n")
                .addStatement("return $T.copyOf(this.items)", Set.class)
                .build());

        // Funktionale Evolution: plus, plusAll, minus
        classBuilder.addMethod(MethodSpec.methodBuilder("plus")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(itemType, "item")
                .addStatement("$T.requireNonNull(item, $S)", Objects.class, "item must not be null")
                .addStatement("$T copy = mutableCopy()", arrayListOfItems)
                .addStatement("copy.add(item)")
                .addStatement("return new $T(copy)", selfType)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("plusAll")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(ParameterizedTypeName.get(ClassName.get(Iterable.class), itemType), "others")
                .addStatement("$T.requireNonNull(others, $S)", Objects.class, "others must not be null")
                .addStatement("$T copy = mutableCopy()", arrayListOfItems)
                .addStatement("others.forEach(copy::add)")
                .addStatement("return new $T(copy)", selfType)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("minus")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(itemType, "item")
                .addStatement("$T.requireNonNull(item, $S)", Objects.class, "item must not be null")
                .addStatement("$T copy = mutableCopy()", arrayListOfItems)
                .addStatement("copy.remove(item)")
                .addStatement("return new $T(copy)", selfType)
                .build());

        // filter(Predicate<Item>)
        TypeName predicateType = ParameterizedTypeName.get(ClassName.get(Predicate.class), itemType);
        classBuilder.addMethod(MethodSpec.methodBuilder("filter")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(predicateType, "predicate")
                .addStatement("$T.requireNonNull(predicate, $S)", Objects.class, "predicate must not be null")
                .addStatement("return new $T(this.items.stream().filter(predicate).toList())", selfType)
                .build());

        // Iterable
        TypeName iteratorType = ParameterizedTypeName.get(ClassName.get(Iterator.class), itemType);
        classBuilder.addMethod(MethodSpec.methodBuilder("iterator")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(iteratorType)
                .addStatement("return this.items.iterator()")
                .build());

        TypeName consumerType = ParameterizedTypeName.get(ClassName.get(Consumer.class), WildcardTypeName.supertypeOf(itemType));
        classBuilder.addMethod(MethodSpec.methodBuilder("forEach")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .addParameter(consumerType, "action")
                .addStatement("this.items.forEach(action)")
                .build());

        // Custom Methoden
        if (node.collection().isPresent()) {
            for (MethodNode customMethod : node.collection().get().customMethods()) {
                classBuilder.addMethod(buildCustomMethod(customMethod, targetPackage, explicitImports));
            }
        }

        // equals, hashCode, toString
        classBuilder.addMethod(MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(Object.class, "o")
                .addStatement("if (this == o) return true")
                .addStatement("if (o == null || getClass() != o.getClass()) return false")
                .addStatement("$T that = ($T) o", selfType, selfType)
                .addStatement("return $T.equals(this.items, that.items)", Objects.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class)
                .addStatement("return $T.hash(this.items)", Objects.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return $S + this.items.toString()", collectionClassName)
                .build());

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    public JavaFile generate(EntityNode node, String basePackage, List<String> explicitImports) {
        String targetPackage = PackageResolver.resolveCollectionPackage(basePackage, node.collection(), node.customPackage());
        String itemClassName = node.name();
        String collectionClassName = determineCollectionClassName(node);

        ClassName itemType = ClassName.get(targetPackage, itemClassName);
        ClassName selfType = ClassName.get(targetPackage, collectionClassName);

        TypeName listOfItems = ParameterizedTypeName.get(ClassName.get(List.class), itemType);
        TypeName collectionOfItems = ParameterizedTypeName.get(ClassName.get(Collection.class), itemType);
        TypeName iterableOfItems = ParameterizedTypeName.get(ClassName.get(Iterable.class), itemType);
        TypeName setOfItems = ParameterizedTypeName.get(ClassName.get(Set.class), itemType);
        TypeName arrayListOfItems = ParameterizedTypeName.get(ClassName.get(ArrayList.class), itemType);

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(collectionClassName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(iterableOfItems)
                .addJavadoc("First-class domain collection for {@link $T}. Generated by Vernac DSL Compiler. Do not edit.\n", itemType);

        // Internes Feld: private final List<Item> items;
        classBuilder.addField(FieldSpec.builder(listOfItems, "items", Modifier.PRIVATE, Modifier.FINAL).build());

        // Privater Konstruktor mit List.copyOf
        classBuilder.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .addParameter(collectionOfItems, "items")
                .addStatement("$T.requireNonNull(items, $S)", Objects.class, "items must not be null")
                .addStatement("this.items = $T.copyOf(items)", List.class)
                .build());

        // Factories
        classBuilder.addMethod(MethodSpec.methodBuilder("empty")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addStatement("return new $T($T.of())", selfType, List.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .varargs(true)
                .addParameter(ArrayTypeName.of(itemType), "items")
                .addStatement("$T.requireNonNull(items, $S)", Objects.class, "items must not be null")
                .addStatement("return new $T($T.asList(items))", selfType, Arrays.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(collectionOfItems, "items")
                .addStatement("return new $T(items)", selfType)
                .build());

        // Standard-Queries & Immutability Exports
        classBuilder.addMethod(MethodSpec.methodBuilder("mutableCopy")
                .addModifiers(Modifier.PRIVATE)
                .returns(arrayListOfItems)
                .addStatement("return new $T<>(this.items)", ArrayList.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("size")
                .addModifiers(Modifier.PUBLIC)
                .returns(int.class)
                .addStatement("return this.items.size()")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("isEmpty")
                .addModifiers(Modifier.PUBLIC)
                .returns(boolean.class)
                .addStatement("return this.items.isEmpty()")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("contains")
                .addModifiers(Modifier.PUBLIC)
                .returns(boolean.class)
                .addParameter(itemType, "item")
                .addStatement("return this.items.contains(item)")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("stream")
                .addModifiers(Modifier.PUBLIC)
                .returns(ParameterizedTypeName.get(ClassName.get(Stream.class), itemType))
                .addStatement("return this.items.stream()")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("toList")
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfItems)
                .addJavadoc("Returns an unmodifiable list of the underlying items.\n")
                .addStatement("return this.items")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("elements")
                .addModifiers(Modifier.PUBLIC)
                .returns(listOfItems)
                .addJavadoc("Returns an unmodifiable list of the underlying elements.\n")
                .addStatement("return this.items")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("toSet")
                .addModifiers(Modifier.PUBLIC)
                .returns(setOfItems)
                .addJavadoc("Returns an unmodifiable set of the underlying items.\n")
                .addStatement("return $T.copyOf(this.items)", Set.class)
                .build());

        // Funktionale Evolution: plus, plusAll, minus
        classBuilder.addMethod(MethodSpec.methodBuilder("plus")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(itemType, "item")
                .addStatement("$T.requireNonNull(item, $S)", Objects.class, "item must not be null")
                .addStatement("$T copy = mutableCopy()", arrayListOfItems)
                .addStatement("copy.add(item)")
                .addStatement("return new $T(copy)", selfType)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("plusAll")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(ParameterizedTypeName.get(ClassName.get(Iterable.class), itemType), "others")
                .addStatement("$T.requireNonNull(others, $S)", Objects.class, "others must not be null")
                .addStatement("$T copy = mutableCopy()", arrayListOfItems)
                .addStatement("others.forEach(copy::add)")
                .addStatement("return new $T(copy)", selfType)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("minus")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(itemType, "item")
                .addStatement("$T.requireNonNull(item, $S)", Objects.class, "item must not be null")
                .addStatement("$T copy = mutableCopy()", arrayListOfItems)
                .addStatement("copy.remove(item)")
                .addStatement("return new $T(copy)", selfType)
                .build());

        // Exklusiv für Entities: minusId(id)
        TypeName idType = TypeResolver.resolve(node.idDefinition().type(), targetPackage, explicitImports);
        classBuilder.addMethod(MethodSpec.methodBuilder("minusId")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(idType, "id")
                .addStatement("$T.requireNonNull(id, $S)", Objects.class, "id must not be null")
                .addStatement("return new $T(this.items.stream().filter(item -> !item.id().equals(id)).toList())", selfType)
                .build());

        // filter(Predicate<Item>)
        TypeName predicateType = ParameterizedTypeName.get(ClassName.get(Predicate.class), itemType);
        classBuilder.addMethod(MethodSpec.methodBuilder("filter")
                .addModifiers(Modifier.PUBLIC)
                .returns(selfType)
                .addParameter(predicateType, "predicate")
                .addStatement("$T.requireNonNull(predicate, $S)", Objects.class, "predicate must not be null")
                .addStatement("return new $T(this.items.stream().filter(predicate).toList())", selfType)
                .build());

        // Iterable
        TypeName iteratorType = ParameterizedTypeName.get(ClassName.get(Iterator.class), itemType);
        classBuilder.addMethod(MethodSpec.methodBuilder("iterator")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(iteratorType)
                .addStatement("return this.items.iterator()")
                .build());

        TypeName consumerType = ParameterizedTypeName.get(ClassName.get(Consumer.class), WildcardTypeName.supertypeOf(itemType));
        classBuilder.addMethod(MethodSpec.methodBuilder("forEach")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .addParameter(consumerType, "action")
                .addStatement("this.items.forEach(action)")
                .build());

        // Custom Methoden
        if (node.collection().isPresent()) {
            for (MethodNode customMethod : node.collection().get().customMethods()) {
                classBuilder.addMethod(buildCustomMethod(customMethod, targetPackage, explicitImports));
            }
        }

        // equals, hashCode, toString
        classBuilder.addMethod(MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(Object.class, "o")
                .addStatement("if (this == o) return true")
                .addStatement("if (o == null || getClass() != o.getClass()) return false")
                .addStatement("$T that = ($T) o", selfType, selfType)
                .addStatement("return $T.equals(this.items, that.items)", Objects.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class)
                .addStatement("return $T.hash(this.items)", Objects.class)
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return $S + this.items.toString()", collectionClassName)
                .build());

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildCustomMethod(MethodNode method, String targetPackage, List<String> explicitImports) {
        TypeName returnType = TypeResolver.resolve(method.returnType(), targetPackage, explicitImports);
        MethodSpec.Builder builder = MethodSpec.methodBuilder(method.name())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType);

        for (FieldNode param : method.parameters()) {
            TypeName paramType = TypeResolver.resolve(param.type(), targetPackage, explicitImports);
            builder.addParameter(paramType, param.name());
        }

        builder.addCode(method.bodyCode() + "\n");
        return builder.build();
    }

    public String determineCollectionClassName(EntityNode node) {
        if (node.collection().isPresent() && node.collection().get().customName().isPresent()) {
            return node.collection().get().customName().get();
        }
        return pluralize(node.name());
    }

    public String determineCollectionClassName(ValueObjectNode node) {
        if (node.collection().isPresent() && node.collection().get().customName().isPresent()) {
            return node.collection().get().customName().get();
        }
        return pluralize(node.name());
    }

    private String pluralize(String name) {
        if (name.endsWith("y") && !name.endsWith("ay") && !name.endsWith("ey") && !name.endsWith("oy") && !name.endsWith("uy")) {
            return name.substring(0, name.length() - 1) + "ies";
        }
        if (name.endsWith("s") || name.endsWith("x") || name.endsWith("z") || name.endsWith("ch") || name.endsWith("sh")) {
            return name + "es";
        }
        return name + "s";
    }
}