// Copyright 2026 Danny Reinhold
// SPDX-License-Identifier: Apache-2.0

package org.vernac.compiler.generator;

import com.palantir.javapoet.*;
import org.jspecify.annotations.Nullable;
import org.vernac.compiler.ast.*;
import org.vernac.compiler.util.TypeUtils;
import org.vernac.runtime.DomainValidationException;
import org.vernac.runtime.Entity;

import javax.lang.model.element.Modifier;
import java.util.*;

public class EntityGenerator {
    private final org.vernac.compiler.pipeline.ResolvedProject project;
    public EntityGenerator() { this.project = null; }
    public EntityGenerator(org.vernac.compiler.pipeline.ResolvedProject project) { this.project = project; }
    private TypeName resolve(TypeNode type, String targetPackage) {
        return project == null ? TypeResolver.resolve(type, targetPackage)
                : ResolvedJavaTypes.javaType(project.typeOf(type));
    }


    private static final ClassName ENTITY_INTERFACE = ClassName.get(Entity.class);
    private static final ClassName NULLABLE_ANNOTATION = ClassName.get(Nullable.class);

    public JavaFile generate(EntityNode node, Map<String, ValueObjectNode> valueObjects, Map<String, EntityNode> entities, String basePackage, List<String> imports) {
        String targetPackage = PackageResolver.resolveDomainPackage(basePackage, node.customPackage());
        String className = node.name();
        ClassName selfType = ClassName.get(targetPackage, className);

        TypeName idType = resolve(node.idDefinition().type(), targetPackage);
        String idFieldName = node.idDefinition().fieldName();

        ParameterizedTypeName entityInterfaceType = ParameterizedTypeName.get(ENTITY_INTERFACE, idType);

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(entityInterfaceType)
                .addJavadoc("Domain Entity generated by Vernac DSL Compiler. Do not edit.\n");

        // Legacy schema entry point only. Reviewed domain generation does not assume a DB mapping.
        if (project == null) {
            String tableName = PostgresSchemaUtils.resolveTableName(className);
            String idColName = PostgresSchemaUtils.resolveColumnName(idFieldName);
            String ddl = PostgresSchemaUtils.generateEntityDdl(tableName, idColName, node.fields(), valueObjects, entities, targetPackage);
            classBuilder.addJavadoc("\n<p>Expected PostgreSQL Table Schema:</p>\n<pre>{@code\n$L\n}</pre>\n", ddl);
            classBuilder.addField(FieldSpec.builder(String.class, "TABLE_NAME", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$S", tableName).build());
            classBuilder.addField(FieldSpec.builder(String.class, "SCHEMA_DDL", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$S", ddl).build());
        }

        // 1. ID-Feld (immer final)
        classBuilder.addField(FieldSpec.builder(idType, idFieldName, Modifier.PRIVATE, Modifier.FINAL).build());

        // 2. Nutzlast-Felder
        for (FieldNode field : node.fields()) {
            TypeName fieldType = resolve(field.type(), targetPackage);
            List<Modifier> modifiers = new ArrayList<>();
            modifiers.add(Modifier.PRIVATE);
            if (!field.isMutable()) {
                modifiers.add(Modifier.FINAL);
            }

            FieldSpec.Builder fieldBuilder = FieldSpec.builder(fieldType, field.name(), modifiers.toArray(Modifier[]::new));
            if (field.type().isOptional()) {
                fieldBuilder.addAnnotation(NULLABLE_ANNOTATION);
            }
            classBuilder.addField(fieldBuilder.build());
        }

        // 3. Privater Konstruktor
        classBuilder.addMethod(buildPrivateConstructor(node, targetPackage, idType, idFieldName));

        // 4. Validierungsmethode
        classBuilder.addMethod(project != null && !node.validations().isEmpty()
                ? ValidationGenerator.delegate(selfType) : buildValidateMethod(node));

        // 5. create(...) Factory
        classBuilder.addMethod(buildCreateFactory(node, targetPackage, selfType, idType, idFieldName));

        // 6. reconstitute(...) Factory
        classBuilder.addMethod(buildReconstituteFactory(node, targetPackage, selfType, idType, idFieldName));

        // 7. fromExternal(...) Factory
        if (project == null) classBuilder.addMethod(buildFromExternalFactory(node, targetPackage, selfType, idType, idFieldName));

        // 8. Automatische Mutatoren im Record-Stil für veränderliche Felder
        Set<String> explicitMethodNames = node.methods().stream()
                .map(MethodNode::name)
                .collect(java.util.stream.Collectors.toSet());

        for (FieldNode field : node.fields()) {
            if (project == null && field.isMutable() && !explicitMethodNames.contains(field.name())) {
                classBuilder.addMethod(buildDomainMutator(field, targetPackage));
            }
        }

        // 9. Eigene Methoden aus DSL
        if (project == null) {
            for (MethodNode method : node.methods()) classBuilder.addMethod(buildCustomMethod(method, targetPackage));
        } else {
            classBuilder.addAnnotation(org.jspecify.annotations.NullMarked.class);
            new DomainAccessGenerator().addTo(classBuilder, MutableDomain.of(node).orElseThrow(), selfType, project);
        }

        // 10. Getter
        classBuilder.addMethod(buildIdGetter(idType, idFieldName));

        for (FieldNode field : node.fields()) {
            classBuilder.addMethod(buildFieldGetter(field, targetPackage));
        }

        // 11. equals, hashCode (auf ID-Basis) & toString
        classBuilder.addMethod(buildEquals(selfType, idFieldName));
        classBuilder.addMethod(buildHashCode(idFieldName));
        classBuilder.addMethod(buildToString(className, idFieldName));

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildPrivateConstructor(EntityNode node, String packageName, TypeName idType, String idFieldName) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .addParameter(idType, idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = resolve(field.type(), packageName);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            constructor.addParameter(param.build());
        }

        constructor.addParameter(boolean.class, "validate");

        constructor.beginControlFlow("if ($N == null)", idFieldName)
                .addStatement("throw new $T($S)", DomainValidationException.class, node.name() + ".id must not be null")
                .endControlFlow().addStatement("this.$N = $N", idFieldName, idFieldName);

        for (FieldNode field : node.fields()) {
            if (field.type().isOptional()) {
                constructor.addStatement("this.$N = $N", field.name(), field.name());
            } else if (TypeUtils.isPrimitive(field.type().name())) {
                constructor.addStatement("this.$N = $N", field.name(), field.name());
            } else {
                constructor.beginControlFlow("if ($N == null)", field.name())
                        .addStatement("throw new $T($S)", DomainValidationException.class, node.name() + "." + field.name() + " must not be null")
                        .endControlFlow().addStatement("this.$N = $N", field.name(), field.name());
            }
        }

        constructor.beginControlFlow("if (validate)");
        constructor.addStatement("validate()");
        constructor.endControlFlow();

        return constructor.build();
    }

    private MethodSpec buildValidateMethod(EntityNode node) {
        MethodSpec.Builder validate = MethodSpec.methodBuilder("validate")
                .addModifiers(Modifier.PRIVATE);

        for (ValidationRuleNode rule : node.validations()) {
            validate.beginControlFlow("if (!($L))", rule.condition());
            validate.addStatement("throw new $T($S)", DomainValidationException.class, rule.message());
            validate.endControlFlow();
        }

        return validate.build();
    }

    private MethodSpec buildCreateFactory(EntityNode node, String targetPackage, ClassName selfType, TypeName idType, String idFieldName) {
        MethodSpec.Builder create = MethodSpec.methodBuilder("create")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType);

        List<String> passArgs = new ArrayList<>();
        passArgs.add(idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            create.addParameter(param.build());
            passArgs.add(field.name());
        }

        passArgs.add("true");
        create.addStatement("$T $N = $T.create()", idType, idFieldName, idType);
        create.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return create.build();
    }

    private MethodSpec buildReconstituteFactory(EntityNode node, String targetPackage, ClassName selfType, TypeName idType, String idFieldName) {
        MethodSpec.Builder reconstitute = MethodSpec.methodBuilder("reconstitute")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(idType, idFieldName);

        List<String> passArgs = new ArrayList<>();
        passArgs.add(idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            reconstitute.addParameter(param.build());
            passArgs.add(field.name());
        }

        passArgs.add(project == null ? "false" : "true");
        reconstitute.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return reconstitute.build();
    }

    private MethodSpec buildDomainMutator(FieldNode field, String targetPackage) {
        TypeName type = resolve(field.type(), targetPackage);
        MethodSpec.Builder setter = MethodSpec.methodBuilder(field.name())
                .addModifiers(Modifier.PUBLIC);

        ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());

        if (field.type().isOptional()) {
            param.addAnnotation(NULLABLE_ANNOTATION);
            setter.addParameter(param.build());
            setter.beginControlFlow("if ($T.equals(this.$N, $N))", Objects.class, field.name(), field.name());
            setter.addStatement("return");
            setter.endControlFlow();
            setter.addStatement("this.$N = $N", field.name(), field.name());
        } else if (TypeUtils.isPrimitive(field.type().name())) {
            setter.addParameter(param.build());
            setter.beginControlFlow("if (this.$N == $N)", field.name(), field.name());
            setter.addStatement("return");
            setter.endControlFlow();
            setter.addStatement("this.$N = $N", field.name(), field.name());
        } else {
            setter.addParameter(param.build());
            setter.addStatement("$T.requireNonNull($N, $S)", Objects.class, field.name(), field.name() + " must not be null");
            setter.beginControlFlow("if ($T.equals(this.$N, $N))", Objects.class, field.name(), field.name());
            setter.addStatement("return");
            setter.endControlFlow();
            setter.addStatement("this.$N = $N", field.name(), field.name());
        }

        setter.addStatement("validate()");
        return setter.build();
    }

    private MethodSpec buildCustomMethod(MethodNode method, String targetPackage) {
        TypeName returnType = resolve(method.returnType(), targetPackage);
        MethodSpec.Builder builder = MethodSpec.methodBuilder(method.name())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType);

        for (FieldNode param : method.parameters()) {
            TypeName paramType = resolve(param.type(), targetPackage);
            builder.addParameter(paramType, param.name());
        }

        builder.addCode(method.bodyCode() + "\n");
        return builder.build();
    }

    private MethodSpec buildIdGetter(TypeName idType, String idFieldName) {
        return MethodSpec.methodBuilder("id")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(idType)
                .addStatement("return this.$N", idFieldName)
                .build();
    }


    private MethodSpec buildFieldGetter(FieldNode field, String targetPackage) {
        TypeName baseType = resolve(field.type(), targetPackage);
        MethodSpec.Builder getter = MethodSpec.methodBuilder(field.name())
                .addModifiers(Modifier.PUBLIC);

        if (field.type().isOptional()) {
            TypeName optionalType = ParameterizedTypeName.get(ClassName.get(Optional.class), baseType);
            getter.returns(optionalType);
            getter.addStatement("return $T.ofNullable(this.$N)", Optional.class, field.name());
        } else {
            getter.returns(baseType);
            getter.addStatement("return this.$N", field.name());
        }

        return getter.build();
    }

    private MethodSpec buildEquals(ClassName selfType, String idFieldName) {
        return MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(ParameterSpec.builder(Object.class, "o").addAnnotation(Nullable.class).build())
                .addStatement("if (this == o) return true")
                .addStatement("if (o == null || getClass() != o.getClass()) return false")
                .addStatement("$T that = ($T) o", selfType, selfType)
                .addStatement("return $T.equals(this.$N, that.$N)", Objects.class, idFieldName, idFieldName)
                .build();
    }

    private MethodSpec buildHashCode(String idFieldName) {
        return MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class)
                .addStatement("return $T.hash(this.$N)", Objects.class, idFieldName)
                .build();
    }

    private MethodSpec buildToString(String className, String idFieldName) {
        return MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return $S + this.$N + \"]\"", className + "[id=", idFieldName)
                .build();
    }

    private MethodSpec buildFromExternalFactory(EntityNode node, String targetPackage, ClassName selfType, TypeName idType, String idFieldName) {
        MethodSpec.Builder fromExternal = MethodSpec.methodBuilder("fromExternal")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(idType, idFieldName);

        List<String> passArgs = new ArrayList<>();
        passArgs.add(idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            fromExternal.addParameter(param.build());
            passArgs.add(field.name());
        }

        passArgs.add("true");

        fromExternal.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return fromExternal.build();
    }
}