package org.vernac.compiler.generator;

import com.squareup.javapoet.*;
import org.jspecify.annotations.Nullable;
import org.vernac.compiler.ast.EntityNode;
import org.vernac.compiler.ast.FieldNode;
import org.vernac.compiler.ast.MethodNode;
import org.vernac.compiler.ast.ValidationRuleNode;
import org.vernac.runtime.DomainValidationException;
import org.vernac.runtime.Entity;

import javax.lang.model.element.Modifier;
import java.util.*;

public class EntityGenerator {

    private static final ClassName ENTITY_INTERFACE = ClassName.get(Entity.class);
    private static final ClassName NULLABLE_ANNOTATION = ClassName.get(Nullable.class);

    public JavaFile generate(EntityNode node, String packageName) {
        String className = node.name();
        ClassName selfType = ClassName.get(packageName, className);

        TypeName idType = TypeResolver.resolve(node.idDefinition().type(), packageName);
        String idFieldName = node.idDefinition().fieldName();

        ParameterizedTypeName entityInterfaceType = ParameterizedTypeName.get(ENTITY_INTERFACE, idType);

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(entityInterfaceType)
                .addJavadoc("Domain Entity generated by Vernac DSL Compiler. Do not edit.\n");

        // 1. ID-Feld (immer final)
        classBuilder.addField(FieldSpec.builder(idType, idFieldName, Modifier.PRIVATE, Modifier.FINAL).build());

        // 2. Nutzlast-Felder
        for (FieldNode field : node.fields()) {
            TypeName fieldType = TypeResolver.resolve(field.type(), packageName);
            List<Modifier> modifiers = new ArrayList<>();
            modifiers.add(Modifier.PRIVATE);
            if (!field.isMutable()) {
                modifiers.add(Modifier.FINAL);
            }

            FieldSpec.Builder fieldBuilder = FieldSpec.builder(fieldType, field.name(), modifiers.toArray(Modifier[]::new));
            if (field.type().isOptional()) {
                fieldBuilder.addAnnotation(NULLABLE_ANNOTATION);
            }
            classBuilder.addField(fieldBuilder.build());
        }

        // 3. Privater Konstruktor
        classBuilder.addMethod(buildPrivateConstructor(node, packageName, idType, idFieldName));

        // 4. Validierungsmethode
        classBuilder.addMethod(buildValidateMethod(node));

        // 5. create(...) Factory
        classBuilder.addMethod(buildCreateFactory(node, packageName, selfType, idType, idFieldName));

        // 6. reconstitute(...) Factory
        classBuilder.addMethod(buildReconstituteFactory(node, packageName, selfType, idType, idFieldName));

        // 7. Private Setter für mut-Felder
        for (FieldNode field : node.fields()) {
            if (field.isMutable()) {
                classBuilder.addMethod(buildPrivateSetter(field, packageName));
            }
        }

        // 8. Eigene Methoden aus DSL
        for (MethodNode method : node.methods()) {
            classBuilder.addMethod(buildCustomMethod(method, packageName));
        }

        // 9. Getter
        classBuilder.addMethod(buildIdGetter(idType, idFieldName));
        if (!"id".equals(idFieldName)) {
            classBuilder.addMethod(buildCustomIdAliasGetter(idType, idFieldName));
        }

        for (FieldNode field : node.fields()) {
            classBuilder.addMethod(buildFieldGetter(field, packageName));
        }

        // 10. equals, hashCode (auf ID-Basis) & toString
        classBuilder.addMethod(buildEquals(selfType, idFieldName));
        classBuilder.addMethod(buildHashCode(idFieldName));
        classBuilder.addMethod(buildToString(className, idFieldName));

        return JavaFile.builder(packageName, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildPrivateConstructor(EntityNode node, String packageName, TypeName idType, String idFieldName) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .addParameter(idType, idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), packageName);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            constructor.addParameter(param.build());
        }

        constructor.addParameter(boolean.class, "validate");

        constructor.addStatement("this.$N = $T.requireNonNull($N, $S)", idFieldName, Objects.class, idFieldName, idFieldName + " must not be null");

        for (FieldNode field : node.fields()) {
            if (field.type().isOptional()) {
                constructor.addStatement("this.$N = $N", field.name(), field.name());
            } else {
                constructor.addStatement("this.$N = $T.requireNonNull($N, $S)", field.name(), Objects.class, field.name(), field.name() + " must not be null");
            }
        }

        constructor.beginControlFlow("if (validate)");
        constructor.addStatement("validate()");
        constructor.endControlFlow();

        return constructor.build();
    }

    private MethodSpec buildValidateMethod(EntityNode node) {
        MethodSpec.Builder validate = MethodSpec.methodBuilder("validate")
                .addModifiers(Modifier.PRIVATE);

        for (ValidationRuleNode rule : node.validations()) {
            validate.beginControlFlow("if (!($L))", rule.condition());
            validate.addStatement("throw new $T($S)", DomainValidationException.class, rule.message());
            validate.endControlFlow();
        }

        return validate.build();
    }

    private MethodSpec buildCreateFactory(EntityNode node, String packageName, ClassName selfType, TypeName idType, String idFieldName) {
        MethodSpec.Builder create = MethodSpec.methodBuilder("create")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(idType, idFieldName);

        List<String> passArgs = new ArrayList<>();
        passArgs.add(idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), packageName);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            create.addParameter(param.build());
            passArgs.add(field.name());
        }

        passArgs.add("true");
        create.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return create.build();
    }

    private MethodSpec buildReconstituteFactory(EntityNode node, String packageName, ClassName selfType, TypeName idType, String idFieldName) {
        MethodSpec.Builder reconstitute = MethodSpec.methodBuilder("reconstitute")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(idType, idFieldName);

        List<String> passArgs = new ArrayList<>();
        passArgs.add(idFieldName);

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), packageName);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            reconstitute.addParameter(param.build());
            passArgs.add(field.name());
        }

        passArgs.add("false");
        reconstitute.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return reconstitute.build();
    }

    private MethodSpec buildPrivateSetter(FieldNode field, String packageName) {
        String capitalized = field.name().substring(0, 1).toUpperCase(Locale.ROOT) + field.name().substring(1);
        TypeName type = TypeResolver.resolve(field.type(), packageName);

        MethodSpec.Builder setter = MethodSpec.methodBuilder("set" + capitalized)
                .addModifiers(Modifier.PRIVATE);

        ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
        if (field.type().isOptional()) {
            param.addAnnotation(NULLABLE_ANNOTATION);
            setter.addParameter(param.build());
            setter.addStatement("this.$N = $N", field.name(), field.name());
        } else {
            setter.addParameter(param.build());
            setter.addStatement("this.$N = $T.requireNonNull($N, $S)", field.name(), Objects.class, field.name(), field.name() + " must not be null");
        }

        setter.addStatement("validate()");
        return setter.build();
    }

    private MethodSpec buildCustomMethod(MethodNode method, String packageName) {
        TypeName returnType = TypeResolver.resolve(method.returnType(), packageName);
        MethodSpec.Builder builder = MethodSpec.methodBuilder(method.name())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType);

        for (FieldNode param : method.parameters()) {
            TypeName paramType = TypeResolver.resolve(param.type(), packageName);
            builder.addParameter(paramType, param.name());
        }

        builder.addCode(method.bodyCode() + "\n");
        return builder.build();
    }

    private MethodSpec buildIdGetter(TypeName idType, String idFieldName) {
        return MethodSpec.methodBuilder("id")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(idType)
                .addStatement("return this.$N", idFieldName)
                .build();
    }

    private MethodSpec buildCustomIdAliasGetter(TypeName idType, String idFieldName) {
        return MethodSpec.methodBuilder(idFieldName)
                .addModifiers(Modifier.PUBLIC)
                .returns(idType)
                .addStatement("return this.$N", idFieldName)
                .build();
    }

    private MethodSpec buildFieldGetter(FieldNode field, String packageName) {
        TypeName baseType = TypeResolver.resolve(field.type(), packageName);
        MethodSpec.Builder getter = MethodSpec.methodBuilder(field.name())
                .addModifiers(Modifier.PUBLIC);

        if (field.type().isOptional()) {
            TypeName optionalType = ParameterizedTypeName.get(ClassName.get(Optional.class), baseType);
            getter.returns(optionalType);
            getter.addStatement("return $T.ofNullable(this.$N)", Optional.class, field.name());
        } else {
            getter.returns(baseType);
            getter.addStatement("return this.$N", field.name());
        }

        return getter.build();
    }

    private MethodSpec buildEquals(ClassName selfType, String idFieldName) {
        return MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(Object.class, "o")
                .addStatement("if (this == o) return true")
                .addStatement("if (o == null || getClass() != o.getClass()) return false")
                .addStatement("$T that = ($T) o", selfType, selfType)
                .addStatement("return $T.equals(this.$N, that.$N)", Objects.class, idFieldName, idFieldName)
                .build();
    }

    private MethodSpec buildHashCode(String idFieldName) {
        return MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class)
                .addStatement("return $T.hash(this.$N)", Objects.class, idFieldName)
                .build();
    }

    private MethodSpec buildToString(String className, String idFieldName) {
        return MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return $S + this.$N + \"]\"", className + "[id=", idFieldName)
                .build();
    }
}