package org.vernac.compiler.generator;

import com.squareup.javapoet.*;
import org.jspecify.annotations.Nullable;
import org.vernac.compiler.ast.EventNode;
import org.vernac.compiler.ast.FieldNode;
import org.vernac.compiler.util.TypeUtils;
import org.vernac.runtime.DomainEvent;

import javax.lang.model.element.Modifier;
import java.time.Instant;
import java.util.*;

public class EventGenerator {

    private static final ClassName DOMAIN_EVENT_INTERFACE = ClassName.get(DomainEvent.class);
    private static final ClassName NULLABLE_ANNOTATION = ClassName.get(Nullable.class);

    public JavaFile generate(EventNode node, String basePackage, List<String> imports) {
        String targetPackage = PackageResolver.resolveDomainPackage(basePackage, node.customPackage());
        String className = node.name();
        ClassName selfType = ClassName.get(targetPackage, className);
        String eventTypeConstant = toUpperSnakeCase(className);

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(DOMAIN_EVENT_INTERFACE)
                .addJavadoc("Domain Event generated by Vernac DSL Compiler. Do not edit.\n");

        // 1. Statische Konstante: EVENT_TYPE
        classBuilder.addField(FieldSpec.builder(String.class, "EVENT_TYPE", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("$S", eventTypeConstant)
                .build());

        // 2. Basis-Metadaten-Felder
        classBuilder.addField(FieldSpec.builder(UUID.class, "eventId", Modifier.PRIVATE, Modifier.FINAL).build());
        classBuilder.addField(FieldSpec.builder(Instant.class, "occurredOn", Modifier.PRIVATE, Modifier.FINAL).build());

        // 3. Nutzlast-Felder
        for (FieldNode field : node.fields()) {
            TypeName fieldType = TypeResolver.resolve(field.type(), targetPackage);
            FieldSpec.Builder fieldBuilder = FieldSpec.builder(fieldType, field.name(), Modifier.PRIVATE, Modifier.FINAL);
            if (field.type().isOptional()) {
                fieldBuilder.addAnnotation(NULLABLE_ANNOTATION);
            }
            classBuilder.addField(fieldBuilder.build());
        }

        // 4. Privater Konstruktor
        classBuilder.addMethod(buildPrivateConstructor(node, targetPackage));

        // 5. Factory-Methoden: create(...)
        for (MethodSpec factory : buildCreateFactories(node, targetPackage, selfType)) {
            classBuilder.addMethod(factory);
        }

        // 6. Factory-Methode: of(...) (für Replay/Deserialisierung)
        classBuilder.addMethod(buildOfFactory(node, targetPackage, selfType));

        // 7. Getter (Metadaten & Nutzlast)
        classBuilder.addMethod(MethodSpec.methodBuilder("eventId")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(UUID.class)
                .addStatement("return this.eventId")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("occurredOn")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(Instant.class)
                .addStatement("return this.occurredOn")
                .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("eventType")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return EVENT_TYPE")
                .build());

        for (FieldNode field : node.fields()) {
            classBuilder.addMethod(buildGetter(field, targetPackage));
        }

        // 8. equals, hashCode (auf eventId) & toString (via Getter)
        classBuilder.addMethod(buildEquals(selfType));
        classBuilder.addMethod(buildHashCode());
        classBuilder.addMethod(buildToString(node, className));

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildPrivateConstructor(EventNode node, String targetPackage) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .addParameter(UUID.class, "eventId")
                .addParameter(Instant.class, "occurredOn");

        constructor.addStatement("this.eventId = $T.requireNonNull(eventId, $S)", Objects.class, "eventId must not be null");
        constructor.addStatement("this.occurredOn = $T.requireNonNull(occurredOn, $S)", Objects.class, "occurredOn must not be null");

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
                constructor.addParameter(param.build());
                constructor.addStatement("this.$N = $N", field.name(), field.name());
            } else {
                constructor.addParameter(param.build());
                if (TypeUtils.isPrimitive(field.type().name())) {
                    constructor.addStatement("this.$N = $N", field.name(), field.name());
                } else {
                    constructor.addStatement("this.$N = $T.requireNonNull($N, $S)",
                            field.name(), Objects.class, field.name(), field.name() + " must not be null");
                }
            }
        }

        return constructor.build();
    }

    private List<MethodSpec> buildCreateFactories(EventNode node, String targetPackage, ClassName selfType) {
        List<MethodSpec> factories = new ArrayList<>();

        MethodSpec.Builder fullCreate = MethodSpec.methodBuilder("create")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType);

        List<String> passArgs = new ArrayList<>();
        passArgs.add("$T.randomUUID()");
        passArgs.add("$T.now()");

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            fullCreate.addParameter(param.build());
            passArgs.add(field.name());
        }

        fullCreate.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType, UUID.class, Instant.class);
        factories.add(fullCreate.build());

        boolean hasOptional = node.fields().stream().anyMatch(f -> f.type().isOptional());
        boolean hasRequired = node.fields().stream().anyMatch(f -> !f.type().isOptional());
        if (hasOptional && hasRequired) {
            MethodSpec.Builder requiredOnlyCreate = MethodSpec.methodBuilder("create")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .returns(selfType);

            List<String> callArgs = new ArrayList<>();
            for (FieldNode field : node.fields()) {
                if (!field.type().isOptional()) {
                    TypeName type = TypeResolver.resolve(field.type(), targetPackage);
                    requiredOnlyCreate.addParameter(type, field.name());
                    callArgs.add(field.name());
                } else {
                    callArgs.add("null");
                }
            }
            requiredOnlyCreate.addStatement("return create($L)", String.join(", ", callArgs));
            factories.add(requiredOnlyCreate.build());
        }

        return factories;
    }

    private MethodSpec buildOfFactory(EventNode node, String targetPackage, ClassName selfType) {
        MethodSpec.Builder of = MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(UUID.class, "eventId")
                .addParameter(Instant.class, "occurredOn");

        List<String> passArgs = new ArrayList<>(List.of("eventId", "occurredOn"));

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), targetPackage);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            of.addParameter(param.build());
            passArgs.add(field.name());
        }

        of.addStatement("return new $T(" + String.join(", ", passArgs) + ")", selfType);
        return of.build();
    }

    private MethodSpec buildGetter(FieldNode field, String targetPackage) {
        TypeName baseType = TypeResolver.resolve(field.type(), targetPackage);
        MethodSpec.Builder getter = MethodSpec.methodBuilder(field.name())
                .addModifiers(Modifier.PUBLIC);

        if (field.type().isOptional()) {
            TypeName optionalType = ParameterizedTypeName.get(ClassName.get(Optional.class), baseType);
            getter.returns(optionalType);
            getter.addStatement("return $T.ofNullable(this.$N)", Optional.class, field.name());
        } else {
            getter.returns(baseType);
            getter.addStatement("return this.$N", field.name());
        }

        return getter.build();
    }

    private MethodSpec buildEquals(ClassName selfType) {
        return MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(Object.class, "o")
                .addStatement("if (this == o) return true")
                .addStatement("if (o == null || getClass() != o.getClass()) return false")
                .addStatement("$T that = ($T) o", selfType, selfType)
                .addStatement("return $T.equals(this.eventId, that.eventId)", Objects.class)
                .build();
    }

    private MethodSpec buildHashCode() {
        return MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class)
                .addStatement("return $T.hash(this.eventId)", Objects.class)
                .build();
    }

    private MethodSpec buildToString(EventNode node, String className) {
        MethodSpec.Builder toString = MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class);

        List<String> parts = new ArrayList<>();
        parts.add("\"eventId=\" + this.eventId()");
        parts.add("\"occurredOn=\" + this.occurredOn()");
        parts.add("\"eventType='\" + this.eventType() + \"'\"");

        for (FieldNode field : node.fields()) {
            if (field.type().isOptional()) {
                parts.add("\"" + field.name() + "=\" + this." + field.name() + "().orElse(null)");
            } else {
                parts.add("\"" + field.name() + "=\" + this." + field.name() + "()");
            }
        }

        String returnExpr = "\"" + className + "[\" + " + String.join(" + \", \" + ", parts) + " + \"]\"";
        toString.addStatement("return " + returnExpr);
        return toString.build();
    }

    private String toUpperSnakeCase(String camelCase) {
        return camelCase.replaceAll("([a-z])([A-Z]+)", "$1_$2").toUpperCase(Locale.ROOT);
    }
}