package org.vernac.compiler.generator;

import com.palantir.javapoet.*;
import org.vernac.compiler.ast.IdDeclarationNode;

import javax.lang.model.element.Modifier;
import java.util.Objects;
import java.util.UUID;

public class IdGenerator {
    public JavaFile generate(IdDeclarationNode node, String basePackage) {
        String targetPackage = PackageResolver.resolveDomainPackage(basePackage, node.customPackage());

        String className = node.name();
        ClassName selfType = ClassName.get(targetPackage, className);

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addJavadoc("Domain Identifier generated by Vernac DSL Compiler. Do not edit.\n")
                .addField(FieldSpec.builder(UUID.class, "value", Modifier.PRIVATE, Modifier.FINAL).build());

        // Privater Konstruktor
        classBuilder.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .addParameter(UUID.class, "value")
                .addStatement("this.value = $T.requireNonNull(value, $S)", Objects.class, "value must not be null")
                .build());

        // create() - Erzeugt eine neue ID mit interner UUID
        classBuilder.addMethod(MethodSpec.methodBuilder("create")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addStatement("return new $T($T.randomUUID())", selfType, UUID.class)
                .build());

        // of(UUID) - Für Persistenz / DB-Mapping
        classBuilder.addMethod(MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(UUID.class, "value")
                .addStatement("return new $T(value)", selfType)
                .build());

        // of(String) - Für REST / Parsing
        classBuilder.addMethod(MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(String.class, "value")
                .addStatement("$T.requireNonNull(value, $S)", Objects.class, "value must not be null")
                .addStatement("return new $T($T.fromString(value))", selfType, UUID.class)
                .build());

        // Getter value()
        classBuilder.addMethod(MethodSpec.methodBuilder("value")
                .addModifiers(Modifier.PUBLIC)
                .returns(UUID.class)
                .addStatement("return this.value")
                .build());

        // equals
        classBuilder.addMethod(MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(Object.class, "o")
                .addStatement("if (this == o) return true")
                .addStatement("if (o == null || getClass() != o.getClass()) return false")
                .addStatement("$T that = ($T) o", selfType, selfType)
                .addStatement("return $T.equals(this.value, that.value)", Objects.class)
                .build());

        // hashCode
        classBuilder.addMethod(MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class)
                .addStatement("return $T.hash(this.value)", Objects.class)
                .build());

        // toString
        classBuilder.addMethod(MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return this.value.toString()")
                .build());

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }
}