// Copyright 2026 Danny Reinhold
// SPDX-License-Identifier: Apache-2.0

package org.vernac.compiler.generator;

import com.palantir.javapoet.*;
import org.vernac.compiler.ast.ListenerNode;
import org.vernac.compiler.ast.RawJavaStatementNode;
import org.vernac.compiler.ast.UseDependencyNode;

import javax.lang.model.element.Modifier;
import java.util.List;
import java.util.Objects;

public class ListenerGenerator {

    private static final ClassName COMPONENT_ANNOTATION = ClassName.get("org.springframework.stereotype", "Component");
    private static final ClassName TX_EVENT_LISTENER = ClassName.get("org.springframework.transaction.event", "TransactionalEventListener");
    private static final ClassName TX_PHASE = ClassName.get("org.springframework.transaction.event", "TransactionPhase");

    public JavaFile generate(ListenerNode node, String basePackage, List<String> explicitImports) {
        String targetPackage = PackageResolver.resolveDomainPackage(basePackage, node.customPackage());
        String className = node.listenerName();
        ClassName eventType = ClassName.get(targetPackage, node.eventName());

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(COMPONENT_ANNOTATION)
                .addJavadoc("Domain Event Listener generated by Vernac DSL Compiler. Do not edit.\n");

        // 1. Dependencies als private final Felder & Konstruktor
        MethodSpec.Builder ctor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC);

        for (UseDependencyNode dep : node.dependencies()) {
            TypeName depType = TypeResolver.resolve(
                    new org.vernac.compiler.ast.TypeNode(dep.location(), dep.typeName(), List.of(), false),
                    targetPackage,
                    explicitImports
            );
            String fieldName = dep.instanceName().orElseGet(() -> deriveInstanceName(dep.typeName()));

            classBuilder.addField(FieldSpec.builder(depType, fieldName, Modifier.PRIVATE, Modifier.FINAL).build());

            ctor.addParameter(depType, fieldName);
            ctor.addStatement("this.$N = $T.requireNonNull($N, $S)", fieldName, Objects.class, fieldName, fieldName + " must not be null");
        }

        if (!node.dependencies().isEmpty()) {
            classBuilder.addMethod(ctor.build());
        }

        // 2. Event-Handler Methode on(Event event)
        MethodSpec.Builder onMethod = MethodSpec.methodBuilder("on")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(TX_EVENT_LISTENER)
                        .addMember("phase", "$T.AFTER_COMMIT", TX_PHASE)
                        .build())
                .addParameter(eventType, "event");

        for (RawJavaStatementNode stmt : node.statements()) {
            onMethod.addCode(stmt.javaCode() + "\n");
        }

        classBuilder.addMethod(onMethod.build());

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private String deriveInstanceName(String typeName) {
        if (typeName == null || typeName.isEmpty()) return "dependency";
        return Character.toLowerCase(typeName.charAt(0)) + typeName.substring(1);
    }
}