package org.vernac.compiler.generator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class PackageInfoGenerator {

    public String generateSource(String packageName) {
        return """
                // Generated by Vernac DSL Compiler. Do not edit.
                @org.jspecify.annotations.NullMarked
                package %s;
                """.formatted(packageName);
    }

    public void writeTo(Path outputDirectory, String packageName) throws IOException {
        String packagePath = packageName.replace('.', '/');
        Path targetDir = outputDirectory.resolve(packagePath);
        Files.createDirectories(targetDir);

        Path targetFile = targetDir.resolve("package-info.java");
        Files.writeString(targetFile, generateSource(packageName));
    }
}