// Copyright 2026 Danny Reinhold
// SPDX-License-Identifier: Apache-2.0

package org.vernac.compiler.generator;

import org.vernac.language.VernacNames;

import com.palantir.javapoet.*;
import org.vernac.compiler.ast.*;
import org.vernac.compiler.util.ConditionUtils;
import org.vernac.compiler.util.TypeUtils;
import org.vernac.runtime.DomainValidationException;

import javax.lang.model.element.Modifier;
import java.util.*;

public class UseCaseGenerator {

    private static final ClassName SERVICE_ANNOTATION = ClassName.get("org.springframework.stereotype", "Service");
    private static final ClassName TRANSACTIONAL_ANNOTATION = ClassName.get("org.springframework.transaction.annotation", "Transactional");

    public JavaFile generate(
            UseCaseNode node,
            Map<String, AggregateNode> aggregates,
            Map<String, RepositoryNode> repositories,
            String basePackage,
            List<String> explicitImports
    ) {
        String targetPackage = PackageResolver.resolveUseCasePackage(basePackage, node.customPackage());
        String domainPackage = PackageResolver.resolveDomainPackage(basePackage, Optional.empty());
        String className = node.name();

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(SERVICE_ANNOTATION)
                .addAnnotation(TRANSACTIONAL_ANNOTATION)
                .addJavadoc("UseCase generated by Vernac DSL Compiler. Do not edit.\n");

        // 1. Dependencies als finale Felder anlegen
        Map<String, String> depFieldToType = new LinkedHashMap<>();
        for (UseDependencyNode dep : node.dependencies()) {
            String fieldName = dep.instanceName().orElseGet(() -> deriveDefaultInstanceName(dep.typeName()));
            TypeName type = TypeResolver.resolve(new TypeNode(dep.location(), dep.typeName(), List.of(), false), domainPackage, explicitImports);

            classBuilder.addField(FieldSpec.builder(type, fieldName, Modifier.PRIVATE, Modifier.FINAL).build());
            depFieldToType.put(fieldName, dep.typeName());
        }

        // 2. Konstruktor für Spring-Injection
        classBuilder.addMethod(buildConstructor(node, domainPackage, explicitImports));

        // 3. Optional: Eingebetteter Result-Record für Tupel-Return
        boolean hasTupleReturn = node.returnStatement().isPresent() && node.returnStatement().get() instanceof TupleReturnNode;
        if (hasTupleReturn) {
            TupleReturnNode tuple = (TupleReturnNode) node.returnStatement().get();
            classBuilder.addType(buildEmbeddedResultRecord(tuple, node, aggregates, domainPackage, explicitImports));
        }
        // 4. execute(...) Methode generieren
        classBuilder.addMethod(buildExecuteMethod(node, hasTupleReturn, className, targetPackage, domainPackage, explicitImports));

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildConstructor(UseCaseNode node, String domainPackage, List<String> explicitImports) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC);

        for (UseDependencyNode dep : node.dependencies()) {
            String fieldName = dep.instanceName().orElseGet(() -> deriveDefaultInstanceName(dep.typeName()));
            TypeName type = TypeResolver.resolve(new TypeNode(dep.location(), dep.typeName(), List.of(), false), domainPackage, explicitImports);

            constructor.addParameter(type, fieldName);
            constructor.addStatement("this.$N = $T.requireNonNull($N, $S)", fieldName, Objects.class, fieldName, fieldName + " must not be null");
        }

        return constructor.build();
    }

    private TypeSpec buildEmbeddedResultRecord(
            TupleReturnNode tuple,
            UseCaseNode useCase,
            Map<String, AggregateNode> aggregates,
            String domainPackage,
            List<String> explicitImports
    ) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder();

        for (TupleElementNode elem : tuple.elements()) {
            String fieldName = elem.alias().orElseGet(() -> deriveTupleFieldName(elem.expressionCode()));
            TypeName type = ExpressionTypeInferrer.infer(elem.expressionCode(), useCase, aggregates, domainPackage, explicitImports);
            constructor.addParameter(type, fieldName);
        }

        return TypeSpec.recordBuilder("Result")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .recordConstructor(constructor.build())
                .build();
    }

    private MethodSpec buildExecuteMethod(
            UseCaseNode node,
            boolean hasTupleReturn,
            String className,
            String targetPackage,
            String domainPackage,
            List<String> explicitImports
    ) {
        MethodSpec.Builder execute = MethodSpec.methodBuilder("execute")
                .addModifiers(Modifier.PUBLIC);

        // Rückgabetyp bestimmen
        if (hasTupleReturn) {
            execute.returns(ClassName.get(targetPackage, className, "Result"));
        } else if (node.returnStatement().isPresent() && node.returnStatement().get() instanceof SingleReturnNode single && single.expressionCode().isPresent()) {
            // Default-Fallback für Single-Return, sofern nicht void
            execute.returns(TypeName.get(Object.class));
        } else {
            execute.returns(TypeName.VOID);
        }

        // Parameter entgegennehmen & validieren
        for (FieldNode param : node.parameters()) {
            TypeName type = TypeResolver.resolve(param.type(), domainPackage, explicitImports);
            execute.addParameter(type, param.name());
            if (!param.type().isOptional() && !TypeUtils.isPrimitive(param.type().name())) {
                execute.addStatement("$T.requireNonNull($N, $S)", Objects.class, param.name(), param.name() + " must not be null");
            }
        }

        // Vorbedingungen aus validates { ... }
        for (ValidationRuleNode rule : node.validations()) {
            String msg = rule.message().isBlank() ? "Validation failed for: " + rule.condition() : rule.message();
            execute.beginControlFlow("if ($L)", ConditionUtils.negate(rule.condition()))
                    .addStatement("throw new $T($S)", DomainValidationException.class, msg)
                    .endControlFlow();
        }

        // Map für Standard-Repository-Auflösung (Aggregate -> Repo-Instanzvariable)
        Map<String, String> defaultRepos = new HashMap<>();
        for (UseDependencyNode dep : node.dependencies()) {
            String inst = dep.instanceName().orElseGet(() -> deriveDefaultInstanceName(dep.typeName()));
            if (dep.typeName().endsWith("Repository")) {
                String aggName = dep.typeName().substring(0, dep.typeName().length() - "Repository".length());
                defaultRepos.put(aggName, inst);
            }
        }

        // Statements abarbeiten
        for (UseCaseStatementNode stmt : node.statements()) {
            if (stmt instanceof LoadStatementNode load) {
                String varName = load.instanceName().orElseGet(() -> deriveDefaultInstanceName(load.aggregateType()));
                String repoVar = load.repositoryName().orElseGet(() -> defaultRepos.get(load.aggregateType()));
                String idCode = load.idExpressionCode().orElseGet(() -> deriveDefaultInstanceName(load.aggregateType()) + "Id");

                // Typ des Aggregats sauber als ClassName im domainPackage auflösen:
                TypeName aggregateClass = TypeResolver.resolve(
                        new TypeNode(load.location(), load.aggregateType(), List.of(), false),
                        domainPackage,
                        explicitImports
                );

                // $T statt $L für den Typen nutzen!
                execute.addStatement("$T $L = this.$L.byId($L)", aggregateClass, varName, repoVar, idCode);
            } else if (stmt instanceof SaveStatementNode save) {
                String repoVar = save.repositoryName().orElseGet(() -> {
                    // Falls repo nicht angegeben, suchen wir Repo passend zum Instanznamen
                    return save.instanceName() + "Repository";
                });
                // Fallback falls Instanzname z.B. "order" ist -> Repo ist "orderRepository"
                if (!defaultRepos.containsValue(repoVar)) {
                    repoVar = deriveDefaultInstanceName(save.instanceName()) + "Repository";
                }
                execute.addStatement("this.$L.save($L)", repoVar, save.instanceName());
            } else if (stmt instanceof RawJavaStatementNode raw) {
                execute.addCode("$L\n", raw.javaCode());
            }
        }

        // Return Statement ausführen
        if (hasTupleReturn) {
            TupleReturnNode tuple = (TupleReturnNode) node.returnStatement().get();
            List<String> values = tuple.elements().stream().map(TupleElementNode::expressionCode).toList();
            execute.addStatement("return new Result($L)", String.join(", ", values));
        } else if (node.returnStatement().isPresent() && node.returnStatement().get() instanceof SingleReturnNode single) {
            single.expressionCode().ifPresent(expr -> execute.addStatement("return $L", expr));
        }

        return execute.build();
    }

    private String deriveDefaultInstanceName(String typeName) {
        if (typeName == null || typeName.isEmpty()) return "value";
        return VernacNames.lowerFirst(typeName);
    }

    private String deriveTupleFieldName(String code) {
        int lastDot = code.lastIndexOf('.');
        if (lastDot >= 0) {
            String after = code.substring(lastDot + 1).replaceAll("[^\\p{javaJavaIdentifierPart}]", "");
            return after.isEmpty() ? "value" : after;
        }
        return "value";
    }
}