// Copyright 2026 Danny Reinhold
// SPDX-License-Identifier: Apache-2.0

package org.vernac.compiler.generator;

import com.palantir.javapoet.*;
import org.jspecify.annotations.Nullable;
import org.jspecify.annotations.NullMarked;
import org.vernac.compiler.pipeline.ResolvedProject;
import org.vernac.compiler.symbols.TypeIdentity;
import org.vernac.compiler.ast.FieldNode;
import org.vernac.compiler.ast.MethodNode;
import org.vernac.compiler.ast.ValidationRuleNode;
import org.vernac.compiler.ast.ValueObjectNode;
import org.vernac.runtime.DomainValidationException;
import org.vernac.runtime.ValueObject;

import javax.lang.model.element.Modifier;
import java.util.*;

public class ValueObjectGenerator {

    private static final ClassName VALUE_OBJECT_INTERFACE = ClassName.get(ValueObject.class);
    private static final ClassName VALIDATION_EXCEPTION = ClassName.get(DomainValidationException.class);
    private static final AnnotationSpec NULLABLE_ANNOTATION = AnnotationSpec.builder(Nullable.class).build();

    public JavaFile generate(ValueObjectNode node, String namespace, ResolvedProject project) {
        String targetPackage = ResolvedJavaTypes.domainClass(new TypeIdentity(namespace, node.name())).packageName();

        if (node.isEnum()) {
            return generateEnum(node, targetPackage, project);
        }

        String className = node.name();
        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(VALUE_OBJECT_INTERFACE)
                .addAnnotation(NullMarked.class)
                .addJavadoc("Value object generated by Vernac DSL Compiler. Do not edit.\n");

        for (FieldNode field : node.fields()) {
            TypeName fieldType = ResolvedJavaTypes.javaType(project.typeOf(field.type()));
            if (field.type().isOptional()) fieldType = fieldType.annotated(NULLABLE_ANNOTATION);
            classBuilder.addField(FieldSpec.builder(fieldType, field.name(), Modifier.PRIVATE, Modifier.FINAL).build());
        }

        classBuilder.addMethod(buildPrivateConstructor(node, project));

        if (!node.validations().isEmpty()) {
            classBuilder.addMethod(buildValidateMethod(node));
        }

        for (MethodSpec factory : buildFactoryMethods(node, targetPackage, className, project)) {
            classBuilder.addMethod(factory);
        }

        if (node.fields().size() == 1) {
            FieldNode singleField = node.fields().getFirst();
            for (MethodSpec helper : buildSingleValueHelpers(singleField, className, targetPackage, project)) {
                classBuilder.addMethod(helper);
            }
        }

        for (FieldNode field : node.fields()) {
            classBuilder.addMethod(buildGetter(field, project));
        }

        classBuilder.addMethod(buildEquals(node, className));
        classBuilder.addMethod(buildHashCode(node));
        classBuilder.addMethod(buildToString(node, className));

        for (MethodNode method : node.methods()) {
            classBuilder.addMethod(buildCustomMethod(method, project));
        }

        return JavaFile.builder(targetPackage, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private JavaFile generateEnum(ValueObjectNode node, String targetPackage, ResolvedProject project) {
        String enumName = node.name();
        ClassName selfType = ClassName.get(targetPackage, enumName);

        TypeSpec.Builder enumBuilder = TypeSpec.enumBuilder(enumName)
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(VALUE_OBJECT_INTERFACE)
                .addAnnotation(NullMarked.class)
                .addJavadoc("Enum Value object generated by Vernac DSL Compiler. Do not edit.\n");

        // 1. Enum-Konstanten anlegen
        for (var constant : node.enumConstants()) {
            enumBuilder.addEnumConstant(
                    constant.name(),
                    TypeSpec.anonymousClassBuilder("$S", constant.effectiveDbValue()).build()
            );
        }

        // 2. Feld dbValue
        enumBuilder.addField(FieldSpec.builder(String.class, "dbValue", Modifier.PRIVATE, Modifier.FINAL).build());

        // 3. Konstruktor
        enumBuilder.addMethod(MethodSpec.constructorBuilder()
                .addParameter(String.class, "dbValue")
                .addStatement("this.dbValue = $T.requireNonNull(dbValue, $S)", Objects.class, "dbValue must not be null")
                .build());

        // 4. dbValue() Getter
        enumBuilder.addMethod(MethodSpec.methodBuilder("dbValue")
                .addModifiers(Modifier.PUBLIC)
                .returns(String.class)
                .addStatement("return this.dbValue")
                .build());

        // 5. of(String) Factory
        MethodSpec.Builder ofFactory = MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType)
                .addParameter(String.class, "value")
                .addStatement("$T.requireNonNull(value, $S)", Objects.class, "value must not be null")
                .addStatement("String trimmed = value.trim()")
                .beginControlFlow("for ($T constant : values())", selfType)
                .beginControlFlow("if (constant.dbValue.equalsIgnoreCase(trimmed) || constant.name().equalsIgnoreCase(trimmed))")
                .addStatement("return constant")
                .endControlFlow()
                .endControlFlow()
                .addStatement("throw new $T($S + value)", VALIDATION_EXCEPTION, "Unknown " + enumName + ": ");
        enumBuilder.addMethod(ofFactory.build());

        // 6. toString()
        enumBuilder.addMethod(MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return this.dbValue")
                .build());

        // 7. Eigene DSL-Methoden
        for (MethodNode method : node.methods()) {
            enumBuilder.addMethod(buildCustomMethod(method, project));
        }

        return JavaFile.builder(targetPackage, enumBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildPrivateConstructor(ValueObjectNode node, ResolvedProject project) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE);
        for (FieldNode field : node.fields()) {
            TypeName type = ResolvedJavaTypes.javaType(project.typeOf(field.type()));
            ParameterSpec.Builder param = ParameterSpec.builder(
                    field.type().isOptional() ? type.annotated(NULLABLE_ANNOTATION) : type, field.name());
            if (!field.type().isOptional() && !type.isPrimitive()) {
                constructor.beginControlFlow("if ($N == null)", field.name())
                        .addStatement("throw new $T($S)", VALIDATION_EXCEPTION,
                                node.name() + "." + field.name() + " must not be null")
                        .endControlFlow();
            }
            constructor.addParameter(param.build());
        }
        for (FieldNode field : node.fields()) {
            constructor.addStatement("this.$N = $N", field.name(), field.name());
        }
        if (!node.validations().isEmpty()) constructor.addStatement("validate()");
        return constructor.build();
    }

    private MethodSpec buildValidateMethod(ValueObjectNode node) {
        MethodSpec.Builder validate = MethodSpec.methodBuilder("validate")
                .addModifiers(Modifier.PRIVATE);

        for (ValidationRuleNode rule : node.validations()) {
            String msg = rule.message().isBlank() ? "Validation failed for: " + rule.condition() : rule.message();
            validate.beginControlFlow("if (!($L))", rule.condition())
                    .addStatement("throw new $T($S)", VALIDATION_EXCEPTION, node.name() + ": " + msg)
                    .endControlFlow();
        }

        return validate.build();
    }

    private List<MethodSpec> buildFactoryMethods(ValueObjectNode node, String targetPackage, String className, ResolvedProject project) {
        List<MethodSpec> factories = new ArrayList<>();
        ClassName selfType = ClassName.get(targetPackage, className);

        MethodSpec.Builder fullFactory = MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType);

        List<String> argNames = new ArrayList<>();
        for (FieldNode field : node.fields()) {
            TypeName type = ResolvedJavaTypes.javaType(project.typeOf(field.type()));
            fullFactory.addParameter(field.type().isOptional() ? type.annotated(NULLABLE_ANNOTATION) : type, field.name());
            argNames.add(field.name());
        }
        fullFactory.addStatement("return new $T($L)", selfType, String.join(", ", argNames));
        factories.add(fullFactory.build());

        boolean hasOptional = node.fields().stream().anyMatch(f -> f.type().isOptional());
        boolean hasRequired = node.fields().stream().anyMatch(f -> !f.type().isOptional());
        if (hasOptional && hasRequired) {
            MethodSpec.Builder requiredOnlyFactory = MethodSpec.methodBuilder("of")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .returns(selfType);

            List<String> callArgs = new ArrayList<>();
            for (FieldNode field : node.fields()) {
                if (!field.type().isOptional()) {
                    TypeName type = ResolvedJavaTypes.javaType(project.typeOf(field.type()));
                    requiredOnlyFactory.addParameter(type, field.name());
                    callArgs.add(field.name());
                } else {
                    callArgs.add("null");
                }
            }
            requiredOnlyFactory.addStatement("return new $T($L)", selfType, String.join(", ", callArgs));
            factories.add(requiredOnlyFactory.build());
        }

        return factories;
    }

    private List<MethodSpec> buildSingleValueHelpers(FieldNode field, String className, String targetPackage, ResolvedProject project) {
        List<MethodSpec> helpers = new ArrayList<>();
        ClassName selfType = ClassName.get(targetPackage, className);
        TypeName type = ResolvedJavaTypes.javaType(project.typeOf(field.type()));
        boolean optional = field.type().isOptional();
        if (ClassName.get(UUID.class).equals(type)) {
            helpers.add(MethodSpec.methodBuilder("create").addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .returns(selfType).addStatement("return new $T($T.randomUUID())", selfType, UUID.class).build());
            helpers.add(UuidFactoryMethods.fromString(selfType, field.name(), optional));
            helpers.add(MethodSpec.methodBuilder("asUuid").addModifiers(Modifier.PUBLIC)
                    .returns(optional ? ParameterizedTypeName.get(Optional.class, UUID.class) : ClassName.get(UUID.class))
                    .addStatement("return $N()", field.name()).build());
            MethodSpec.Builder asString = MethodSpec.methodBuilder("asString").addModifiers(Modifier.PUBLIC)
                    .returns(optional ? ParameterizedTypeName.get(Optional.class, String.class) : ClassName.get(String.class));
            if (optional) asString.addStatement("return $N().map($T::toString)", field.name(), UUID.class);
            else asString.addStatement("return $N().toString()", field.name());
            helpers.add(asString.build());
        } else if (ClassName.get(String.class).equals(type)) {
            helpers.add(MethodSpec.methodBuilder("asString").addModifiers(Modifier.PUBLIC)
                    .returns(optional ? ParameterizedTypeName.get(Optional.class, String.class) : ClassName.get(String.class))
                    .addStatement("return $N()", field.name()).build());
        }
        return helpers;
    }

    private MethodSpec buildGetter(FieldNode field, ResolvedProject project) {
        TypeName baseType = ResolvedJavaTypes.javaType(project.typeOf(field.type()));
        MethodSpec.Builder getter = MethodSpec.methodBuilder(field.name())
                .addModifiers(Modifier.PUBLIC);

        if (field.type().isOptional()) {
            TypeName optionalType = ParameterizedTypeName.get(ClassName.get(Optional.class), baseType);
            getter.returns(optionalType);
            getter.addStatement("return $T.ofNullable(this.$N)", Optional.class, field.name());
        } else {
            getter.returns(baseType);
            getter.addStatement("return this.$N", field.name());
        }

        return getter.build();
    }

    private MethodSpec buildEquals(ValueObjectNode node, String className) {
        MethodSpec.Builder equals = MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(ParameterSpec.builder(TypeName.get(Object.class).annotated(NULLABLE_ANNOTATION), "o").build());

        equals.addStatement("if (this == o) return true");
        equals.addStatement("if (o == null || getClass() != o.getClass()) return false");
        equals.addStatement("$L that = ($L) o", className, className);

        List<String> comparisons = new ArrayList<>();
        for (FieldNode field : node.fields()) {
            comparisons.add("$T.equals(this." + field.name() + ", that." + field.name() + ")");
        }

        String statement = "return " + String.join("\n    && ", comparisons);
        Object[] args = Collections.nCopies(node.fields().size(), Objects.class).toArray();
        equals.addStatement(statement, args);

        return equals.build();
    }

    private MethodSpec buildHashCode(ValueObjectNode node) {
        MethodSpec.Builder hashCode = MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class);

        List<String> names = node.fields().stream().map(f -> "this." + f.name()).toList();
        hashCode.addStatement("return $T.hash($L)", Objects.class, String.join(", ", names));
        return hashCode.build();
    }

    private MethodSpec buildToString(ValueObjectNode node, String className) {
        MethodSpec.Builder toString = MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class);

        List<String> fieldFormats = new ArrayList<>();
        for (FieldNode field : node.fields()) {
            fieldFormats.add("\"" + field.name() + "='\" + this." + field.name() + " + \"'\"");
        }

        String returnExpr = "\"" + className + "[\" + " + String.join(" + \", \" + ", fieldFormats) + " + \"]\"";
        toString.addStatement("return " + returnExpr);
        return toString.build();
    }

    private MethodSpec buildCustomMethod(MethodNode method, ResolvedProject project) {
        TypeName returnType = ResolvedJavaTypes.javaType(project.typeOf(method.returnType()));
        if (method.returnType().isOptional()) {
            returnType = ParameterizedTypeName.get(ClassName.get(Optional.class), returnType);
        }
        MethodSpec.Builder builder = MethodSpec.methodBuilder(method.name())
                .addModifiers(Modifier.valueOf(method.accessModifier().toUpperCase(Locale.ROOT)))
                .returns(returnType);
        for (FieldNode param : method.parameters()) {
            TypeName parameterType = ResolvedJavaTypes.javaType(project.typeOf(param.type()));
            if (param.type().isOptional()) parameterType = parameterType.annotated(NULLABLE_ANNOTATION);
            builder.addParameter(parameterType, param.name());
        }
        builder.addCode("$L\n", method.bodyCode());
        return builder.build();
    }
}
