package org.vernac.compiler.generator;

import com.squareup.javapoet.*;
import org.jspecify.annotations.Nullable;
import org.vernac.compiler.ast.FieldNode;
import org.vernac.compiler.ast.ValidationRuleNode;
import org.vernac.compiler.ast.ValueObjectNode;
import org.vernac.runtime.DomainValidationException;
import org.vernac.runtime.ValueObject;

import javax.lang.model.element.Modifier;
import java.util.*;

public class ValueObjectGenerator {

    private static final ClassName VALUE_OBJECT_INTERFACE = ClassName.get(ValueObject.class);
    private static final ClassName VALIDATION_EXCEPTION = ClassName.get(DomainValidationException.class);
    private static final ClassName NULLABLE_ANNOTATION = ClassName.get(Nullable.class);

    public JavaFile generate(ValueObjectNode node, String packageName) {
        String className = node.name();
        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(VALUE_OBJECT_INTERFACE)
                .addJavadoc("Value object generated by Vernac DSL Compiler. Do not edit.\n");

        // 1. Felder
        for (FieldNode field : node.fields()) {
            TypeName fieldType = TypeResolver.resolve(field.type(), packageName);
            FieldSpec.Builder fieldBuilder = FieldSpec.builder(fieldType, field.name(), Modifier.PRIVATE, Modifier.FINAL);
            if (field.type().isOptional()) {
                fieldBuilder.addAnnotation(NULLABLE_ANNOTATION);
            }
            classBuilder.addField(fieldBuilder.build());
        }

        // 2. Privater Konstruktor
        classBuilder.addMethod(buildPrivateConstructor(node, packageName));

        // 3. Validierungsmethode (falls require(...) deklariert)
        if (!node.validations().isEmpty()) {
            classBuilder.addMethod(buildValidateMethod(node));
        }

        // 4. of(...) Factory-Methoden
        for (MethodSpec factory : buildFactoryMethods(node, packageName, className)) {
            classBuilder.addMethod(factory);
        }

        // 5. Single-Value Komfortmethoden (create, asString, etc.)
        if (node.fields().size() == 1) {
            FieldNode singleField = node.fields().getFirst();
            for (MethodSpec helper : buildSingleValueHelpers(singleField, className, packageName)) {
                classBuilder.addMethod(helper);
            }
        }

        // 6. Getter (Record-Style)
        for (FieldNode field : node.fields()) {
            classBuilder.addMethod(buildGetter(field, packageName));
        }

        // 7. equals, hashCode, toString
        classBuilder.addMethod(buildEquals(node, className));
        classBuilder.addMethod(buildHashCode(node));
        classBuilder.addMethod(buildToString(node, className));

        return JavaFile.builder(packageName, classBuilder.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private MethodSpec buildPrivateConstructor(ValueObjectNode node, String packageName) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE);

        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), packageName);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
                constructor.addParameter(param.build());
                constructor.addStatement("this.$N = $N", field.name(), field.name());
            } else {
                constructor.addParameter(param.build());
                if (isCollectionType(field.type().name())) {
                    constructor.addStatement("this.$N = $T.copyOf($T.requireNonNull($N, $S))",
                            field.name(), type instanceof ParameterizedTypeName p ? p.rawType : type,
                            Objects.class, field.name(), field.name() + " must not be null");
                } else {
                    constructor.addStatement("this.$N = $T.requireNonNull($N, $S)",
                            field.name(), Objects.class, field.name(), field.name() + " must not be null");
                }
            }
        }

        if (!node.validations().isEmpty()) {
            constructor.addStatement("validate()");
        }

        return constructor.build();
    }

    private MethodSpec buildValidateMethod(ValueObjectNode node) {
        MethodSpec.Builder validate = MethodSpec.methodBuilder("validate")
                .addModifiers(Modifier.PRIVATE);

        for (ValidationRuleNode rule : node.validations()) {
            String msg = rule.message().isBlank() ? "Validation failed for: " + rule.condition() : rule.message();
            validate.beginControlFlow("if (!($L))", rule.condition())
                    .addStatement("throw new $T($S)", VALIDATION_EXCEPTION, msg)
                    .endControlFlow();
        }

        return validate.build();
    }

    private List<MethodSpec> buildFactoryMethods(ValueObjectNode node, String packageName, String className) {
        List<MethodSpec> factories = new ArrayList<>();
        ClassName selfType = ClassName.get(packageName, className);

        // Volle of(...) Methode
        MethodSpec.Builder fullFactory = MethodSpec.methodBuilder("of")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(selfType);

        List<String> argNames = new ArrayList<>();
        for (FieldNode field : node.fields()) {
            TypeName type = TypeResolver.resolve(field.type(), packageName);
            ParameterSpec.Builder param = ParameterSpec.builder(type, field.name());
            if (field.type().isOptional()) {
                param.addAnnotation(NULLABLE_ANNOTATION);
            }
            fullFactory.addParameter(param.build());
            argNames.add(field.name());
        }
        fullFactory.addStatement("return new $T($L)", selfType, String.join(", ", argNames));
        factories.add(fullFactory.build());

        // Komfort-Factory: of(...) ohne optionale Parameter, falls optionale Felder existieren
        boolean hasOptional = node.fields().stream().anyMatch(f -> f.type().isOptional());
        boolean hasRequired = node.fields().stream().anyMatch(f -> !f.type().isOptional());
        if (hasOptional && hasRequired) {
            MethodSpec.Builder requiredOnlyFactory = MethodSpec.methodBuilder("of")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .returns(selfType);

            List<String> callArgs = new ArrayList<>();
            for (FieldNode field : node.fields()) {
                if (!field.type().isOptional()) {
                    TypeName type = TypeResolver.resolve(field.type(), packageName);
                    requiredOnlyFactory.addParameter(type, field.name());
                    callArgs.add(field.name());
                } else {
                    callArgs.add("null");
                }
            }
            requiredOnlyFactory.addStatement("return new $T($L)", selfType, String.join(", ", callArgs));
            factories.add(requiredOnlyFactory.build());
        }

        return factories;
    }

    private List<MethodSpec> buildSingleValueHelpers(FieldNode field, String className, String packageName) {
        List<MethodSpec> helpers = new ArrayList<>();
        ClassName selfType = ClassName.get(packageName, className);
        String rawTypeName = field.type().name();

        if ("UUID".equals(rawTypeName)) {
            helpers.add(MethodSpec.methodBuilder("create")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .returns(selfType)
                    .addStatement("return new $T($T.randomUUID())", selfType, UUID.class)
                    .build());

            helpers.add(MethodSpec.methodBuilder("of")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .returns(selfType)
                    .addParameter(String.class, "value")
                    .addStatement("$T.requireNonNull(value, $S)", Objects.class, "value must not be null")
                    .addStatement("return new $T($T.fromString(value))", selfType, UUID.class)
                    .build());

            helpers.add(MethodSpec.methodBuilder("asUuid")
                    .addModifiers(Modifier.PUBLIC)
                    .returns(UUID.class)
                    .addStatement("return this.$N", field.name())
                    .build());

            helpers.add(MethodSpec.methodBuilder("asString")
                    .addModifiers(Modifier.PUBLIC)
                    .returns(String.class)
                    .addStatement("return this.$N.toString()", field.name())
                    .build());
        } else if ("String".equals(rawTypeName)) {
            helpers.add(MethodSpec.methodBuilder("asString")
                    .addModifiers(Modifier.PUBLIC)
                    .returns(String.class)
                    .addStatement("return this.$N", field.name())
                    .build());
        }

        return helpers;
    }

    private MethodSpec buildGetter(FieldNode field, String packageName) {
        TypeName baseType = TypeResolver.resolve(field.type(), packageName);
        MethodSpec.Builder getter = MethodSpec.methodBuilder(field.name())
                .addModifiers(Modifier.PUBLIC);

        if (field.type().isOptional()) {
            TypeName optionalType = ParameterizedTypeName.get(ClassName.get(Optional.class), baseType);
            getter.returns(optionalType);
            getter.addStatement("return $T.ofNullable(this.$N)", Optional.class, field.name());
        } else {
            getter.returns(baseType);
            getter.addStatement("return this.$N", field.name());
        }

        return getter.build();
    }

    private MethodSpec buildEquals(ValueObjectNode node, String className) {
        MethodSpec.Builder equals = MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(Object.class, "o");

        equals.addStatement("if (this == o) return true");
        equals.addStatement("if (o == null || getClass() != o.getClass()) return false");
        equals.addStatement("$L that = ($L) o", className, className);

        if (node.fields().isEmpty()) {
            equals.addStatement("return true");
            return equals.build();
        }

        List<String> comparisons = new ArrayList<>();
        for (FieldNode field : node.fields()) {
            comparisons.add("$T.equals(this." + field.name() + ", that." + field.name() + ")");
        }

        String statement = "return " + String.join("\n    && ", comparisons);
        Object[] args = Collections.nCopies(node.fields().size(), Objects.class).toArray();
        equals.addStatement(statement, args);

        return equals.build();
    }

    private MethodSpec buildHashCode(ValueObjectNode node) {
        MethodSpec.Builder hashCode = MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class);

        if (node.fields().isEmpty()) {
            hashCode.addStatement("return 0");
            return hashCode.build();
        }

        List<String> names = node.fields().stream().map(f -> "this." + f.name()).toList();
        hashCode.addStatement("return $T.hash($L)", Objects.class, String.join(", ", names));
        return hashCode.build();
    }

    private MethodSpec buildToString(ValueObjectNode node, String className) {
        MethodSpec.Builder toString = MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class);

        if (node.fields().isEmpty()) {
            toString.addStatement("return $S", className + "[]");
            return toString.build();
        }

        List<String> fieldFormats = new ArrayList<>();
        List<String> fieldVars = new ArrayList<>();
        for (FieldNode field : node.fields()) {
            fieldFormats.add(field.name() + "='\" + this." + field.name() + " + '\"'");
        }

        String returnExpr = "\"" + className + "[\" + " + String.join(" + \", \" + ", fieldFormats) + " + \"]\"";
        toString.addStatement("return " + returnExpr);
        return toString.build();
    }

    private boolean isCollectionType(String typeName) {
        return "List".equals(typeName) || "Set".equals(typeName) || "Map".equals(typeName);
    }
}